### ISSUE TITLE
Ratelimit MONTH and YEAR missing

### ISSUE THREAD

**Issue by rpahli** [envoyproxy/go-control-plane#1029]
Hi, 

I miss the rate limit values for `MONTH` and `YEAR`. My expectation is that the sync process uses the latest envoy proto files.
This is the source I'm referring to: https://github.com/envoyproxy/envoy/blob/main/api/envoy/service/ratelimit/v3/rls.proto#L98-L101

**Comment by rpahli** [comment]
ping

**Comment by valerian-roche** [comment]
Hey, envoy API is defined as part of the envoy repository work. Please open an issue in their repository if you want them to add new values. This repository only includes generated go interfaces for those files
