### ISSUE TITLE
Changing the type of snapshots variable in the SimpleCache

### ISSUE THREAD

**Issue by khe0613** [envoyproxy/go-control-plane#1049]
```go
// https://github.com/envoyproxy/go-control-plane/blob/main/pkg/cache/v3/simple.go


type snapshotCache struct {
	watchCount      int64
	deltaWatchCount int64
	log log.Logger
	ads bool
	snapshots map[string]ResourceSnapshot
	status map[string]*statusInfo
	hash NodeHash
	mu sync.RWMutex
}
```
Currently, the `snapshots`(cached resources) variable type in the `Simple` cache is `map`.
And this variable cannot be injected externally via the `NewSnapshotCache()` function.

However, this implementation has a consistency problem in that `snapshots`(cached resources) are not shared between nodes in a distributed environment where the control plane is scaled out. Because the implementation of the `snapshots`(cached resources) variable is forced to be **in-memory**.

So, how about changing the type of the `snapshots` variable to an **interface** with a name like `Snapshots` , and making this implementation injectable via the `NewSnapshotCache()` function?
Here is the example code I'm suggesting:

```go
// https://github.com/envoyproxy/go-control-plane/blob/main/pkg/cache/v3/simple.go


// Abstraction over cached resources
type Snapshots interface {
  AddSnapshot(nodeId string, snapshot ResourceSnapshot)  // Used in the `SetSnapshot()` method of simple cache.
  GetSnapshot(nodeId string)  // Used in several methods of simple cache. (`sendHeartbeats()`, `GetSnapshot()`, `CreateWatch()`, `CreateDeltaWatch()`, `Fetch()`)
}

type snapshotCache struct {
	watchCount      int64
	deltaWatchCount int64
	log log.Logger
	ads bool
	snapshots Snapshots // Changed from `map[string]ResourceSnapshot` type to `Snapshots` type
	status map[string]*statusInfo
	hash NodeHash
	mu sync.RWMutex
}

// Add a `Snapshots` type parameter to allow injecting an implementation of the `snapshots` variable.
func NewSnapshotCache(ads bool, hash NodeHash, snapshots Snapshots, logger log.Logger) SnapshotCache {
	return newSnapshotCache(ads, hash, snapshots, logger)
}
```

&nbsp;

If changed as I suggested, I expect that the implementation of the `snapshot`(cached resources) variable will be freely expandable based on **in-memory**, **distributed cache**, **db**, etc.

If you need any further explanation or have any questions, please let me know. Thank you.

**Comment by valerian-roche** [comment]
Hey, I am unclear on this request. The library currently assumes snapshots to be immutable, so I would expect a distributed cache for snapshots to be implemented on top of the current library. 
The cache state machine cannot only "pull" a snapshot when a node is updated as it also needs to be made aware then updates are done. Is the idea that the `Snapshots` interface would get a "pull" on initial node request and will then send updates when applicable? In such context I would expect a need to "unregister" for updates once no more client is watching the cache.
Overall while I can see this as a way to not have to use callbacks to do such model, I do not believe it cannot be done given the current interface

**Comment by khe0613** [comment]
@valerian-roche 

Sorry for the late reply.

My intention was to change the `snapshots` in the snapshot cache to an interface(`Snapshots`) instead of forcing it to be a `map`, to make it more scalable (distributed cache, etc).

However, I was so focused on the pull on the initial node request that I didn't think about sending updates to the cache to the node.
Please disregard my suggestion.

**Comment by khe0613** [comment]
@valerian-roche 
Lastly, I have a question.
Do you plan to add distributed cache to this library in the future, or are you expecting users of the library to implement it themselves?

**Comment by valerian-roche** [comment]
Hey, I don't think we'd be adding complex caches with external dependencies anytime soon. 
We currently use it as a low level library, and would let users build any more advanced features around it

**Comment by khe0613** [comment]
@valerian-roche 
Thanks for your reply. I'll close this issue!
