### ISSUE TITLE
Can we please have a new tagged release

### ISSUE THREAD

**Issue by davecheney** [envoyproxy/go-control-plane#106]
Hello,

Can we please have a new tagged release to pick up #102

If this tag could be in semver form that would be very helpful in letting me transition my project from Dep to Go 1.11's module system. 

Thank you.

**Comment by kyessenov** [comment]
Is the current tagging system module system-compatible?
Is v0.5 an OK tag, or should we switch to 1.x.y style?

**Comment by davecheney** [comment]
Sadly v0.5 does not conform to the semver spec. It would need to be `v0.5.0`

**Comment by kyessenov** [comment]
Sure. Will do in a moment.

**Comment by davecheney** [comment]
Thank you.

**Comment by kyessenov** [comment]
Done. Let me know if something goes wrong during update.

**Comment by davecheney** [comment]
Perfect. Thank you!
