### ISSUE TITLE
Consider using OpenCensus for monitoring instrumentation

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/go-control-plane#110]
OpenCensus is a library for go that has extensible export backends:
https://github.com/census-instrumentation/opencensus-go

This should be a good choice to keep this library vendor-neutral.

**Comment by taion809** [comment]
@kyessenov 
What specifically would we want to instrument with opencensus?  I did work on integrating opencensus with our inhouse xds server and it was pretty straight forward but a lot of is was on the application code itself instead of threading it through go-control-plane.

**Comment by kyessenov** [comment]
This is a good question, and it is probably more important than the choice of the monitoring library.
Doing it at a higher level is an option, but I believe there are some common needs that could be off-loaded to this library. OpenCensus was motivated as a vendor-neutral shim, since there aren't that many shims for monitoring out there.

Some ideas about what could be useful:
- xDS stats: rejects/accepts, number of xDS requests, number of responses
- config stats: latency on pushing config snapshots
- error stats: xDS rejection reasons

**Comment by taion809** [comment]
Cool that sounds good; can you assign this one to me?
