### ISSUE TITLE
Generating a snapshot from a configuration file

### ISSUE THREAD

**Issue by nakabonne** [envoyproxy/go-control-plane#122]
This is a feature request.
From the conclusion, How about adding a function to generate snapshot from yaml or json file?
Like this:

```go
import "pkg/cache"
func NewSnapshotFromYAML(filePath string) cache.Snapshot {}
```

I think we need the abstracted API, if we want to manage the resource that becomes the response of xDS with yaml.
For example, in case we want to review the data-plane configuration with multiple people, we need to manage them with yaml or json files.

**Comment by alecholmez** [comment]
You can actually do this by using the exported function:
```go
...

	// Update the version since we are commiting a new cache snapshot
	atomic.AddInt32(cs.CacheVersion, 1)

	// Populate our snapshot with the appropriate clusters and listeners
	snapshot := cache.NewSnapshot(fmt.Sprintf("%d", *cs.CacheVersion), endpoints, clusters, routes, listeners)

	cs.Logger.Info().Msgf("New snapshot version: %d", *cs.CacheVersion)

	// Set our snapshot in memory
	return Cache.SetSnapshot(nodeID, snapshot)
}
```
All you have to do is build the `[]cache.Resource` array for each envoy resource type using the generated `envoy` resource proto files in this repo. Here's an example of that:
```go
func ConvertToCacheResources(clusters []*v2.Cluster, listeners []*v2.Listener) map[string][]cache.Resource {
	resources := make(map[string][]cache.Resource, 2)

	var c, l []cache.Resource
	for _, cluster := range clusters {
		c = append(c, cluster)
	}
	for _, listener := range listeners {
		l = append(l, listener)
	}

	resources["clusters"] = c
	resources["listeners"] = l

	return resources
}
```
Obviously you'd do this for endpoints and routes if you need to, but you'd have to handle dealing with the yaml and translating that to the envoy resources. All the logic needed to do this is exposed from the `cache` package.
