### ISSUE TITLE
Merge / accept Rotor, in whole or in part

### ISSUE THREAD

**Issue by trjordan** [envoyproxy/go-control-plane#126]
So with Turbine Labs [going away](https://www.turbinelabs.io/), there's not going to be anybody around to work on [Rotor](https://github.com/turbinelabs/rotor). Rotor is a control plane based on go-control-plane that adds EDS integration with common service discovery registries like Kubernetes, Consul, and AWS (EC2 tags and ECS).

If the Envoy project wants it, it's yours. 

## Why It's Worth Adopting Rotor

**The community needs an out-of-the-box control plane**

Rotor exists based on Turbine Labs' experience trying to get people up and running with Envoy at scale, both as a support vendor and a community member (mostly Slack). Most people figure out quickly that they need a control plane, and they typically disappear for 2-4 weeks trying to write an EDS integration. They generally win the battle (producing a control plane) but lose the war (maintaing the control plane becomes a drag on successfully deploying Envoy everywhere). 

The primary motivation for users is EDS integration with either Consul or Kubernetes. Rotor solves this without writing any code, which has been a huge win for a lot of folks.

In addition, the notion of a centralized control plane has been adopted broadly, and Rotor provides some facility for defining listeners and routes in a single place (a config file for Rotor, which is roughly the same format as Envoy LDS). Many users find this operationally preferable to managing and distributing static config files, as it gets them on a path to use xDS over gRPC quickly. 

## Considerations

Most of these can be overcome with some work, but I'll put all the cards on the table (to the best of my ability).

1) **Rotor used to be commercially backed.** In particular, it has code to connect to the Turbine Labs API, which is no longer functional. It's easy enough to ignore, since that code path is only used when you pass an API key. But perhaps one would want to remove the CLI help text or the code soon after adopting the project.

2) **Rotor's documentation is partially hosted on the Turbine Labs blog.** The blog isn't going away (thanks, Medium!), but one might want to fold [the intro post](https://blog.turbinelabs.io/connect-your-service-discovery-to-envoy-6fbcd1dd0d2a) or [the big update post](https://blog.turbinelabs.io/rotor-a-complete-control-plane-for-envoy-294acb3fc92) into the Rotor's README.

3) **Istio's Pilot has some of the same goals.** Strategically, it may be more interesting to adopt Pilot and put work towards that. Rotor's primary advantage was always with folks with significant non-Kubernetes deployments, and there are a lot of those people out there. I suspect it will be a while before Pilot can be the blessed solution for typical users, because it's going to be a while before most people are 100% on Kubernetes. Even then, Istio's momentum is real, and having two suggested control planes may not be a win for users.

4) **Rotor is not a particularly robust solution for LDS and RDS.** It's just another place to write RDS and LDS configuration. Turbine Labs felt that this was our commercial wheelhouse, so Rotor was never going to, e.g. read routes from Consul tags and set up routes based on that. We've seen users adopt Rotor as a way to configure LDS/RDS with just config file vs. writing code for go-control-plane, but this area of functionality could be much more full-featured.

If you ask me, I think there's value in at least having Rotor brought under the Envoy / CNCF care as a companion project. There's a real need for a more standardized control plane story, whether that's Rotor or some other project. 

Happy to discuss anything else in this issue, if there are other questions or concerns about the project!

**Comment by trjordan** [comment]
cc @mattklein123 @caniszczyk

**Comment by alecholmez** [comment]
I would note that ECS support has issues, especially with http/2 and grpc

**Comment by alecholmez** [comment]
Decipher's Grey Matter actually absorbed the rotor codebase into it's control-plane. We've done extensive modification and robustification (if that's even a word 😅 ). We'd love to have the community check out our platform and we'd also love to get involved in the envoy and xDS communities! @mattklein123 @htuch 

I actually attended EnvoyCon 2019 and found the xDS roadmap and UDPA quite interesting, would love to get involved

**Comment by htuch** [comment]
@alecholmez I suggest joining the next Envoy community call or the Envoy Slack (#xds). You can find details of both at https://github.com/envoyproxy/envoy. Happy to chat more about opportunities to be involved with xDS work.

**Comment by alecholmez** [comment]
@htuch Awesome! Would love to join and chat about some opportunities. @cstrahan I think would like to get involved too
