### ISSUE TITLE
Filter.config_type causes protobuf errors for http_connection_manager since v1.9

### ISSUE THREAD

**Issue by u8983478934** [envoyproxy/go-control-plane#151]
The structure of the `Filter` [message](https://github.com/envoyproxy/envoy/blob/v1.9.0/api/envoy/api/v2/listener/listener.proto#L23) has changed in v1.9 so that `config` became `config_type`. Now I get the error in Envoy's logs when the log level is set to debug

```
gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener fff: Proto constraint validation failed (HttpConnectionManagerValidationError.StatPrefix: ["value length must be at least " '\x01' " bytes"]):


```
even though `StatPrefix` in `HttpConnectionManager` is set properly

here is my http_connection_manager
```go
hcm := envoyhcm.HttpConnectionManager{
		CodecType:  envoyhcm.AUTO,
		StatPrefix: "BLABLABLA",

		RouteSpecifier: &envoyhcm.HttpConnectionManager_RouteConfig{
			RouteConfig: <<<MyRouteConfig>>>,
		},
	}
```

here is my filterChains
```go

anyHCM, err := types.MarshalAny(hcm)

	if err != nil {
		panic(err)
	}

filterChains := []envoylistener.FilterChain{
		envoylistener.FilterChain{
			Filters: []envoylistener.Filter{
				{
					Name: util.HTTPConnectionManager,
					ConfigType: &envoylistener.Filter_TypedConfig{
						TypedConfig: anyHCM,
					},
				},
			},
		},
	}
```

and here is my listener

```go
listener := api.Listener{
		Name:         "my_listener",
		Address:      *mkAddress("127.0.0.1", uint32(4589)),
		FilterChains: *filterChains,
	}
```

I am not sure whether this is a bug but surely this only applies for v1.9+ so maybe `http_connection_manager` isn't properly serialized before sending the response

**Comment by kyessenov** [comment]
You might have better luck asking this in envoy slack/repo.
Proto only cares about field number unless you use JSON as input. So renaming of a proto field should not break wire compatibility.

**Comment by PinZhang** [comment]
+1, got the same error, :(

**Comment by rbkumar88** [comment]
> +1, got the same error, :(

Same error

**Comment by yifan-gu** [comment]
+1 same error

**Comment by skurunji** [comment]
+1 same error :( 

What is the workaround for it ?

**Comment by skurunji** [comment]
Worked when i used envoyproxy/envoy-dev:latest
