### ISSUE TITLE
github.com/envoyproxy/protoc-gen-validate/validate import

### ISSUE THREAD

**Issue by HeinOldewageRetro** [envoyproxy/go-control-plane#168]
`github.com/lyft/protoc-gen-validate/validate` now expects to be imported as `github.com/envoyproxy/protoc-gen-validate/validate`, this causes this package to fail to build.

This is in the case of installing the package using `go get -d github.com/envoyproxy/go-control-plane/...`

**Comment by kyessenov** [comment]
Yes, it moved yesterday. I'll send a PR shortly.
