### ISSUE TITLE
issue with generated validation code: incorrect package import

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/go-control-plane#173]
Reported by @yuval-k :
```
I tried to update this PR, but i'm seeing a generation issue.
specifically, in validate.pb.go files, instead of importing core "github.com/envoyproxy/go-control-plane/envoy/api/v2/core" it imports core "envoy/api/v2/core"
```

**Comment by akshyag** [comment]
I am seeing the same issue

**Comment by LukeShu** [comment]
I am seeing this too.

**Comment by LukeShu** [comment]
Should be "fixed" (worked around) as of the addition of `make generate-patch` in e90fc65c48c6e270d72ab798e0d7c441fcc0a807

**Comment by kyessenov** [comment]
It's really an issue in https://github.com/envoyproxy/protoc-gen-validate.
I can take a look at why it's failing for that particular proto.

**Comment by kyessenov** [comment]
Seems like this is working correctly with golang/protobuf.
