### ISSUE TITLE
HttpConnectionManager.NormalisePath is not present

### ISSUE THREAD

**Issue by davecheney** [envoyproxy/go-control-plane#175]
To enable the path normalisation feature shipped in Envoy 1.9.1 I need to set HttpConnectionManager.NormalisePath but that isn't available yet. When will it be available?

**Comment by kyessenov** [comment]
If this is a new field in data-plane-api, then it should be a matter of regenerating the protos. There's an annoying issue with some imports not respecting importmaps in protoc-gen-validate, which requires a bit of manual patching afterwards.

**Comment by kyessenov** [comment]
v0.7.1 has it.

**Comment by davecheney** [comment]
Thank you!
