### ISSUE TITLE
HTTP PATCH method seems to be unsupported by the library

### ISSUE THREAD

**Issue by glebmish** [envoyproxy/go-control-plane#176]
Hi!

I use PATCH requests that go through envoy and logs are written with als implemented on golang. I expect to see "PATCH" as a result of this code:

```
import (
	envoy "github.com/envoyproxy/go-control-plane/envoy/data/accesslog/v2"
)

func RequestMethod(ent *envoy.HTTPAccessLogEntry) string {
	return ent.GetRequest().GetRequestMethod().String()
}
```

Instead, I see "METHOD_UNSPECIFIED". When I tried to find the reason in the library code, I found that PATCH is not in the list of request methods (https://github.com/envoyproxy/go-control-plane/blob/master/envoy/api/v2/core/base.pb.go#L67)

What do you think about this? Was it omitted intentionally or just missed? Can it be the reason of the problem I described?

Thank you for your help.

**Comment by kyessenov** [comment]
You should probably ask this question in envoy itself. The source of truth is https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/core/base.proto#L132

**Comment by glebmish** [comment]
What's interesting is that envoy itself writes PATCH to logs as expected. Probably it puts data in protobufs only to transfer to als or it's not the reason of the problem. I'll try to add PATCH for both envoy and library to check if it works and open issue there then.

Thank you!

**Comment by glebmish** [comment]
Hi, fixed the issue in envoy. Can we update it here now?
https://github.com/envoyproxy/envoy/issues/6694

**Comment by glebmish** [comment]
Hi, @kyessenov, can you please take a look at the issue I recently closed in Envoy? It affects the library as proto files are the same. As PATCH now added there, it would be good to update files here as well. What do you think?

**Comment by kyessenov** [comment]
Yes, I saw your change. I'm hoping someone can approve https://github.com/envoyproxy/go-control-plane/pull/181 to get the protos flowing. I myself don't have rights to merge PRs without approval.

**Comment by glebmish** [comment]
I see, thanks @kyessenov !

**Comment by glebmish** [comment]
@kyessenov, I see that your PR is merged  and PATCH appeared in protobuf enum. Closing this issue

**Comment by glebmish** [comment]
Hi @kyessenov,

do you know when is the next release? I'd like to have this fix but I guess I can only do this after the release, right?

**Comment by kyessenov** [comment]
You can use SHA of the tip until a release is issued. There's usually one a month. Let me know if you have better idea how to organize release cycles here that works fine with Envoy releases (which are far less frequent).

**Comment by glebmish** [comment]
Thanks @kyessenov, I'll let you know if it worked!

I don't think faster release cycle would be more beneficial than just using SHA for this case, so don't worry about it.
