### ISSUE TITLE
when i use the GrpcJsonTranscoder, envoy happen error

### ISSUE THREAD

**Issue by developersPHP** [envoyproxy/go-control-plane#186]
the ADD_Listener_With_ADS_Route like this :
```
func ADD_Listener_With_ADS_Route(n *NodeConfig) {
	routeResource := &api.RouteConfiguration {
		Name: "ads_route",
		VirtualHosts: []route.VirtualHost{
			route.VirtualHost{
				Name: "local_service",
				Domains: []string{
					"*",
				},
				Routes: []route.Route{
					route.Route{
						Match: route.RouteMatch{
							PathSpecifier: &route.RouteMatch_Prefix{
								Prefix: "/",
							},
							CaseSensitive: &types.BoolValue{
								Value: false,
							},
						},
						Action: &route.Route_Route{
							Route: &route.RouteAction{
								ClusterSpecifier: &route.RouteAction_Cluster{
									Cluster: "cluster_with_ads_endpoint",
								},
								/*HostRewriteSpecifier: &route.RouteAction_HostRewrite{
									HostRewrite: "webshell.com",
								},*/
							},
						},
					},
				},
			},
		},
	}

	/*http_filter_router_ := &http_router.Router{
		DynamicStats: &types.BoolValue{
			Value: true,
		},
	}*/

	grpcJsonTranscoder := &grpc_json_transcoder.GrpcJsonTranscoder {
		DescriptorSet: &grpc_json_transcoder.GrpcJsonTranscoder_ProtoDescriptor{"/data/hello.pb"},
		Services : []string{"reservations.v1.ReservationService"},
		PrintOptions: &grpc_json_transcoder.GrpcJsonTranscoder_PrintOptions{
			AddWhitespace: true,
			AlwaysPrintPrimitiveFields: true,
			AlwaysPrintEnumsAsInts: false,
			PreserveProtoFieldNames: false,
		},
	}

	grpc_transcoder, err := util.MessageToStruct(grpcJsonTranscoder)
	//grpc_transcoder, err := grpcJsonTranscoder.Marshal()
	fmt.Printf("转换器%v", grpc_transcoder)
	if err != nil {
		fmt.Printf("grpc转换器失败%v", err)
		glog.Error(err)
		return
	}


	/*http_filter_router, err := util.MessageToStruct(http_filter_router_)
	if err != nil {
		glog.Error(err)
		return
	}*/

	listen_filter_http_conn_ := &http_conn_manager.HttpConnectionManager {
		StatPrefix: "envoy.http_connection_manager",
		CodecType: http_conn_manager.AUTO, //为什么没有
		RouteSpecifier: &http_conn_manager.HttpConnectionManager_Rds {
			Rds: &http_conn_manager.Rds {
				RouteConfigName: "ads_route",
				ConfigSource: core.ConfigSource{
					ConfigSourceSpecifier: &core.ConfigSource_Ads{
						Ads: &core.AggregatedConfigSource{},
					},
				},
			},
		},
		HttpFilters: []*http_conn_manager.HttpFilter {
			&http_conn_manager.HttpFilter{
				Name: "envoy.router",
				ConfigType: &http_conn_manager.HttpFilter_Config{
					Config: grpc_transcoder,
				},
			},
		},
	}
	listen_filter_http_conn, err := listen_filter_http_conn_.Marshal()
	if err != nil {
		glog.Error(err)
		return
	}

	listenerResources := &api.Listener {
		Name: "listener1",
		Address: core.Address{
			Address: &core.Address_SocketAddress {
				SocketAddress: &core.SocketAddress{
					Protocol: core.TCP, //为什么没有
					Address:  "0.0.0.0",
					PortSpecifier: &core.SocketAddress_PortValue{
						PortValue: 9001,
					},
				},
			},
		},
		FilterChains: []listener.FilterChain {
			listener.FilterChain{
				Filters: []listener.Filter {
					listener.Filter{
						Name: "envoy.http_connection_manager",
						ConfigType: &listener.Filter_TypedConfig {
							TypedConfig: &types.Any{
								TypeUrl: "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager",
								Value:listen_filter_http_conn,
							},
						},
					},
				},
			},
		},
	}

	n.listeners = append(n.listeners, listenerResources)
	n.routes = append(n.routes, routeResource)
}
```

the envoy error report is 

[2019-05-23 10:09:43.654][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:77] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) listener1: Unable to parse JSON as proto (INVALID_ARGUMENT:proto_descriptor: Cannot find field.): {"services":["reservations.v1.ReservationService"],"print_options":{"add_whitespace":true,"always_print_primitive_fields":true},"proto_descriptor":"/data/hello.pb"}
[2019-05-23 10:09:43.655][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:77] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) listener1: Unable to parse JSON as proto (INVALID_ARGUMENT:print_options: Cannot find field.): {"proto_descriptor":"/data/hello.pb","services":["reservations.v1.ReservationService"],"print_options":{"always_print_primitive_fields":true,"add_whitespace":true}}

who can help me slove the problem??

**Comment by developersPHP** [comment]
@kyessenov  can you help me ??

**Comment by kyessenov** [comment]
I think you just have a stale envoy build. There might be new proto fields that your envoy is not aware about. You can try to run with `--allow-unknown-fields` to see if the error goes away, which would confirm it.

**Comment by developersPHP** [comment]
@kyessenov  thank you !!
i had solved it 
because the http_conn_manager httpFilter name must be match a supported filter 

Is there any specific documentation for this project?  o(*￣︶￣*)o

**Comment by developersPHP** [comment]
hi @kyessenov ， what the mean of the annotation.
 how to use AggregatedConfigSource, Can you give me an example??

my envoy config like this
"filters": [
         {
          "name": "envoy.http_connection_manager",
          "typed_config": {
           "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager",
           "stat_prefix": "grpc_json",
           "rds": {
            "config_source": {
             "ads": {}
            },
            "route_config_name": "ads_route"
           },


can you help me ??  

// Aggregated Discovery Service (ADS) options. This is currently empty, but when
// set in :ref:`ConfigSource <envoy_api_msg_core.ConfigSource>` can be used to
// specify that ADS is to be used.
type AggregatedConfigSource struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

**Comment by developersPHP** [comment]
I have sloved the problem。
mark here
the bootstrap config must configur the dynamic_resources、cds_config、lds_config 、ads_config
the config_dump like this:
"rds": {
            "config_source": {
             "ads": {}
            },
            "route_config_name": "local_route"
           },
When the requested resource changes, envoy proactively requests the manager service under the XDS protocol.Fill in the content of ads
