### ISSUE TITLE
Automatically keep data-plane-api version up-to-date

### ISSUE THREAD

**Issue by jessicayuen** [envoyproxy/go-control-plane#190]
Changes are currently being manually pulled in. It will be nice to automate this process through CI or otherwise.

**Comment by kyessenov** [comment]
Unfortunately Envoy does occasionally break the generation script (since we don't use bazel).
But for 80% of time it could and _should_ be automated.

**Comment by kyessenov** [comment]
This was automated by a mirror script in envoyproxy.
