### ISSUE TITLE
build master branch failed

### ISSUE THREAD

**Issue by zplinuxlover** [envoyproxy/go-control-plane#191]
I follow the step to generate go proto file, but it do not work, the error is following

/bin/bash build/generate_protos.sh
Echo Param /Users/gaoshunli/istio/github/go-control-plane/build/../data-plane-api
[error] unable to convert io/envoyproxy/envoy/config/filter/zhaopin/rate_limit/v1/RateLimitValidator.java to proto: template: go:2:14: executing "go" at <.InputPath>: can't evaluate field InputPath in type *pgs.msg
--validate_out: protoc-gen-validate: Plugin failed with status code 1.

the build env is Mac OS

**Comment by zplinuxlover** [comment]
resolve

**Comment by achasveachas** [comment]
@zplinuxlover Do you mind telling us how you resolved it? We're seeing a similar issue while trying to build on Windows:

```
[error] unable to convert io\envoyproxy\envoy\config\filter\network\client_ssl_auth\v2\ClientSSLAuthValidator.java to proto: template: h:2:14: executing "h" at <.InputPath>: can't evaluate field InputPath in type *pgs.msg
--validate_out: protoc-gen-validate: Plugin failed with status code 1. 
Target //source/exe:envoy-static failed to build 
INFO: Elapsed time: 173.177s, Critical Path: 67.98s
INFO: 809 processes: 809 local.  
FAILED: Build did NOT complete successfully   
```

**Comment by kyessenov** [comment]
Please use the fixed SHA of protoc-gen-validate as in go.mod. There's some problem with the latest version. Would appreciate if someone can fix the problem though.

**Comment by EpariNigam** [comment]
How to use that?
