### ISSUE TITLE
Build on master branch failing

### ISSUE THREAD

**Issue by furlongmt** [envoyproxy/go-control-plane#193]
Hi,

When I run "make generate", I get the following error:

/bin/bash build/generate_protos.sh
${MYGOPATH}/go-control-plane/build/../bin/gogofast: program not found or is not executable
--gofast_out: protoc-gen-gogofast: Plugin failed with status code 1. 

There isn't any directory /bin in go-control-plane, and maybe I've overlooked something in the build instructions, but I can't determine how this directory is generated.

**Comment by kyessenov** [comment]
Please take a look at circleci configuration and use the provided docker image for local builds. The binary is in the docker image.

**Comment by furlongmt** [comment]
I get the same error when building from within the container like so:

docker run -v $(pwd):/go-control-plane gcr.io/istio-testing/go-control-plane-ci:05-09-2019 make generate

**Comment by yangminzhu** [comment]
I'm seeing the same error even with the latest image in `./circleci/config.yml`
```shell
$ docker run -it -v $(pwd):/go-control-plane gcr.io/istio-testing/go-control-plane-ci:05-31-2019 make generate
--> vendoring protobufs
go: finding istio.io/gogo-genproto v0.0.0-20190614210408-e88dc8b0e4db
go: downloading istio.io/gogo-genproto v0.0.0-20190614210408-e88dc8b0e4db
go: extracting istio.io/gogo-genproto v0.0.0-20190614210408-e88dc8b0e4db
go: finding github.com/envoyproxy/data-plane-api v0.0.0-20190627184114-829b48c237a2
go: downloading github.com/envoyproxy/data-plane-api v0.0.0-20190627184114-829b48c237a2
go: extracting github.com/envoyproxy/data-plane-api v0.0.0-20190627184114-829b48c237a2
--> generating pb.go files
/bin/bash build/generate_protos.sh
Generating protos /go-control-plane/build/../data-plane-api/envoy/type ...
/go-control-plane/build/../bin/gogofast: program not found or is not executable
--gogofast_out: protoc-gen-gogofast: Plugin failed with status code 1.
Makefile:65: recipe for target 'generate' failed
make: *** [generate] Error 1
```

Also see https://circleci.com/gh/envoyproxy/go-control-plane/441?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by kyessenov** [comment]
The bug here is that bin/gogofast is a local binary, which is a bug.
The script should be using the system one, so changing generate_protos.sh script as in #197 should help.
However, there is another bug with using protoc-gen-validate@0.1.0 which prevents it from use. We'd need to bisect and pick a reasonable build.

**Comment by yangminzhu** [comment]
closing, this should be fixed now. Feel free to reopen if it doesn't work for you.
