### ISSUE TITLE
which data-plane-api version?

### ISSUE THREAD

**Issue by zhengzepeng** [envoyproxy/go-control-plane#203]
When you release a new go-control-plane version，can you point out which data-plane-api version(or commited id) you used in this new version?The better idea is you make some tags in the data-plane-api

**Comment by kyessenov** [comment]
The latest two releases are using cb10255. It's a git submodule in this repo.
We don't have a good semantic version for all of data plane API, so it's hard to assign semantic versions in any reasonable way to this repo If you have thoughts on this, let us know

**Comment by tonyboxes** [comment]
Can add version update changes log?

**Comment by kyessenov** [comment]
The commits from the syncing bot carry envoy SHA.
