### ISSUE TITLE
When a client's fetch is skipped, the reply doesn't contain the correct HTTP status code.

### ISSUE THREAD

**Issue by NickBOA** [envoyproxy/go-control-plane#210]
As outlined in the fix [here](https://github.com/envoyproxy/envoy/pull/6948) and the documentation [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/v2_overview#rest-endpoints), when an `envoyproxy` client initiates a REST fetch and that fetch is skipped (due to a version match), the control plane should reply with a 304 to signal to the client that a skip occurred.

In the current implementation the skip fetch is detected properly, but it simply replies with a general error which has the HTTP status code of 500. This causes the `envoy` client to incorrectly identify the error and log the following warning:

```
[28][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/http_subscription_lib/common/config/http_subscription_impl.h:115] REST config update failed: fetch failure
```

This "skipped fetch" path needs to reply with the newly supported 304.

I have submitted a PR [here](https://github.com/envoyproxy/go-control-plane/pull/209) to solve this issue.

**Comment by kyessenov** [comment]
Should be fixed by https://github.com/envoyproxy/go-control-plane/pull/209
