### ISSUE TITLE
Running into "has no field or method MarshalToSizedBuffer" issue on upgrading to 0.8.6 version

### ISSUE THREAD

**Issue by preethi29** [envoyproxy/go-control-plane#220]
We are trying to upgrade to latest go-control-plane library and we are using dep as dependency management tool. 
We face the following issues while building.
```
vendor/istio.io/gogo-genproto/googleapis/google/rpc/error_details.pb.go:1388:29: m.RetryDelay.MarshalToSizedBuffer undefined (type *types.Duration has no field or method MarshalToSizedBuffer)
vendor/istio.io/gogo-genproto/googleapis/google/rpc/status.pb.go:253:34: m.Details[iNdEx].MarshalToSizedBuffer undefined (type *types.Any has no field or method MarshalToSizedBuffer)
```
Dep installs `1.2.1` version of gogo/protobuf but `MarshalToSizedBuffer` changes are present in unreleased version(master). When we use the revision `28a6bbf47e48e0b2220b2a244750b660c83d4942` of gogo/protobuf, it works fine. 

Is there any reason for using unreleased version of `gogo/protobuf`?

**Comment by kyessenov** [comment]
Thanks for the report. I'll try to look into this in the next version. There's no need to use unreleased version of gogoprotobuf.

**Comment by kyessenov** [comment]
The culprit is istio/gogo-genproto that introduced a version bump and is pulled. We should revert that and use versioned gogo.

**Comment by preethi29** [comment]
Thanks Kuat. Seems like new version of gogo/protobuf  1.3.0 has been
released with the required changes. We can use that one.

**Comment by kyessenov** [comment]
This is a non-issue now that we switched to golang/protobuf. The official library has strict compatibility requirements.
