### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by soheilade** [envoyproxy/go-control-plane#228]
Dear All,

I am trying to register my envoy proxyis in the control plane so that my control plane can get data from my envoy proxies. Could you please elaborate what are the services that I have to register? in the readme file of the repo it is written that register new services as follows 

```
import (
	"google.golang.org/grpc"
	"net"

	api "github.com/envoyproxy/go-control-plane/envoy/api/v2"
	discovery "github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2"
	"github.com/envoyproxy/go-control-plane/pkg/cache"
	xds "github.com/envoyproxy/go-control-plane/pkg/server"
)

func main() {
	snapshotCache := cache.NewSnapshotCache(false, cache.IDHash{}, nil)
	server := xds.NewServer(snapshotCache, nil)
	grpcServer := grpc.NewServer()
	lis, _ := net.Listen("tcp", ":8080")

	discovery.RegisterAggregatedDiscoveryServiceServer(grpcServer, server)
	api.RegisterEndpointDiscoveryServiceServer(grpcServer, server)
	api.RegisterClusterDiscoveryServiceServer(grpcServer, server)
	api.RegisterRouteDiscoveryServiceServer(grpcServer, server)
	api.RegisterListenerDiscoveryServiceServer(grpcServer, server)
	go func() {
		if err := grpcServer.Serve(lis); err != nil {
			// error handling
		}
	}()
}
```

But i am not clear what to replace here. Is there an example that shows how to make this control plane work with envoy proxy?
I appreciate any comment here.
Thanks

**Comment by kyessenov** [comment]
There is pkg/test/main that has a self-contained example. You need to register the services that you want to use, but ADS is usually sufficient.

**Comment by soheilade** [comment]
Thanks @kyessenov , in `main.go`, where the envoy proxy is actually started? and how can i receive data from envoy proxy?

**Comment by stevesloka** [comment]
@soheilade did you get your example running? Happy to help out if you have questions. 

I think your second question might be out of scope for this repo and might be better asked in an istio repo.

**Comment by acnodal-tc** [comment]
aae778b just landed and you might find it helpful.  It's a trivial but functional example.
