### ISSUE TITLE
Switch to gogo from goproto

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/go-control-plane#23]
Is there an interest in switching to gogoprotos from goprotos?
The generated code looks a lot more pleasant to work with (oneofs are terrible in goproto), plus we may get insubstantial performance improvements.

WDYT?

@davecheney @junr03 @rshriram

**Comment by kyessenov** [comment]
Relevant read:
- https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/protobuf.md
- https://github.com/alecthomas/go_serialization_benchmarks

**Comment by davecheney** [comment]
I don’t have a strong position, you’re doing the hard work of maintaining the generated code.

**Comment by roadrunner** [comment]
@kyessenov  check out the [protobuild](https://github.com/stevvooe/protobuild) package. docker swarm using the same approach as well.
example implementation https://github.com/containerd/containerd

**Comment by 9len** [comment]
looks like a much cleaner interface.

**Comment by kyessenov** [comment]
@roadrunner envoy API is using bazel for canonical build system. so all the gogoproto annotations  and codegen will need to be wired through bazel (for better or worse).

**Comment by roadrunner** [comment]
@kyessenov, in my company, we use makefile pretty much for all stuff like the build / test / gen.
i've no clue about bazel, but i'm think that shouldn't be a hard work to get going.

as long as proto files are not changed, you don't need to invoke the generation process.

generating go code from the proto files might be done manually, ie: `make protos`  or  `go list ./... | grep -v vendor | xargs protobuild`

some developers prefer the generation process manually, like; 
`(re)generate -> modify -> check-in -> release`

others preferer CI pipelines, like; 
`modify protos -> check-in -> (ci hooks) (re)generate -> auto commit / tag generated`

**Comment by 9len** [comment]
> i've no clue about bazel, but i'm think that shouldn't be a hard work to get going.

It's not hard work, but neither is it exactly easy.

I think there are really two use cases to consider: 

1) library consumers
2) library contributors

For (1) I think it's pretty important to keep bazel out of the mix, for reasons we've previously discussed (TL;DR go libs should play nice with the standard go toolchain), so I'd definitely advocate for checking in the generated code, and considering it part of the library. 

For (2), I think you can make the claim that the generated code should only change when something in `data-plane-api` changes; might it makes sense to make code generation part of that build/check-in process, producing a package that can then be vendored by `go-control-plane`? That keeps the bazelness associated with api changes constrained to a place that already requires it.

Just my 2¢.

**Comment by davecheney** [comment]
Thanks for doing this, I’m excited to try it out.

**Comment by kyessenov** [comment]
I encourage folks to add gogoproto annotations in data-plane-api where it makes sense (e.g. `nullable`, `stdduration`). I didn't do a full revision, but things will be discovered as we use xDS.

The generation script is mostly automated. I can run it once in awhile manually, since it's fairly simple. Doing automatic multi-repo sync is painful, as we observed first-hand in istio.
