### ISSUE TITLE
The api docs is gone

### ISSUE THREAD

**Issue by hzxuzhonghu** [envoyproxy/go-control-plane#233]
Previously, i can see the comments 
https://github.com/envoyproxy/go-control-plane/blob/094d054b10176dd84506e4f0f65e7f65d8499241/envoy/api/v2/cds.pb.go#L292-L303

Now it is gone

https://github.com/envoyproxy/go-control-plane/blob/786ed9ae4b403fa2f23ad20faa19f4a5e70d15ba/envoy/api/v2/cds.pb.go#L249-L260

**Comment by hzxuzhonghu** [comment]
cc @kyessenov

**Comment by hzxuzhonghu** [comment]
This makes developers hard to understand the api in istio.

**Comment by kyessenov** [comment]
https://github.com/golang/protobuf/issues/666 is the root cause. Closing since it's a problem with the tooling.

**Comment by hzxuzhonghu** [comment]
ok, thanks
