### ISSUE TITLE
Graceful shutdown for the streaming handlers

### ISSUE THREAD

**Issue by jyotimahapatra** [envoyproxy/go-control-plane#237]
We recently had a change for graceful shutdown of the control plane and used `grpc.GracefulStop()` .
`GracefulStop` sends goaway for new connections, but blocks until the current open connections are open. We need a way to add a signal in the handler https://github.com/envoyproxy/go-control-plane/blob/8e1e5558642ae54a35eca889ba37bc550e131216/pkg/server/server.go#L165 to recognize a shutdown and return from the handler.

**Comment by kyessenov** [comment]
Fixed by the PR.
