### ISSUE TITLE
Add the support for caching serialized protobuf bytes of xDS response

### ISSUE THREAD

**Issue by freedomljc** [envoyproxy/go-control-plane#238]
Currently, go-control-plane stores the protobuf format of xDS response in the cache, and [marshals](https://github.com/envoyproxy/go-control-plane/blob/8e1e5558642ae54a35eca889ba37bc550e131216/pkg/server/server.go#L147) it when sending out to envoy. 

If thousands of downstream machines watching the xDS change of one upstream service, it will marshal the same data thousands of times when sending the xDS response to envoy. The issue will get amplified if the xDS of the upstream service gets change very quickly(Especially EDS part).

We noticed that when the upstream services scale up quickly, it causes the cpu spike of go-control-plane server.

To solve the issue, we'll need to add the support of caching serialized xDS response.

**Comment by kyessenov** [comment]
Sounds reasonable. We should probably keep serialized protobufs in the cache plus little metadata.

**Comment by freedomljc** [comment]
@kyessenov , I just sent out the PR https://github.com/envoyproxy/go-control-plane/pull/240, and it is to allow users to marshal the resource while implementing the cache interface. 
Pls let me you your thoughts.

**Comment by lita** [comment]
@freedomljc is it possible to just store marshall responses in the cache vs storing both?

**Comment by freedomljc** [comment]
@lita , from the implementation of go-control-plane, the caching logic is optional, and the built-in caching logic is for the the entry-level usage. We only need to update the interface `CreateWatch` and `Fetch`, and there exist some discussions around it: https://github.com/envoyproxy/go-control-plane/pull/240#discussion_r343329534. pls let me know if your have further questions.
