### ISSUE TITLE
Trigger EDS push whenever CDS changes.

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/go-control-plane#245]
Unfortunately, Envoy has an inconsistency for warming clusters. If a cluster is updated, the endpoints need to be re-pushed even if they don't change, or otherwise, envoy stalls the config.

Example:
1. CDS version c1 for cluster c
2. EDS version e1 for c
3. CDS updated to version v2
4. EDS version e1 for c must be responded even without any change.

@yskopets

**Comment by yskopets** [comment]
@kyessenov Thank you!

That’s exactly the issue we’ve been facing.

It is consistently reproducible when a “snapshot” uses separate versioning for “clusters” and “endpoints”.
