### ISSUE TITLE
Should there be a GetSnapshotKeys just like GetStatusKeys for Cache?

### ISSUE THREAD

**Issue by kathan24** [envoyproxy/go-control-plane#246]
Just like [GetStatusKeys](https://github.com/envoyproxy/go-control-plane/blob/52b167a709f111e6298136064bbaae43419ab22f/pkg/cache/simple.go#L313), wondering if `GetSnapshotKeys` is not implemented for a reason or because there was no need (until now)?

**Comment by kyessenov** [comment]
There was no need yet.
