### ISSUE TITLE
Log Level Overloading

### ISSUE THREAD

**Issue by alecholmez** [envoyproxy/go-control-plane#248]
As of now the logging interface for go-control-plane only exposes `Error` and `Info`. I've seen a few cases where that isn't enough or a user might want more control of the logging level. 

For us specifically we had to overload the Info level to quiet down xDS when we needed too:
```go
type consoleLogger struct{}

func (consoleLogger) Infof(format string, args ...interface{}) {
	// the go-control-plane repo over-utilizes the Info log level causing our xDS logs to become polluted with RPC log statements
	// to supress that we moved their info level to our debug level to reduce the Info level log pollution
	// this logger is passed into the snapshot cache package as it implements their logger interface
	console.Debug().Printf(format, args...)
}

func (consoleLogger) Debugf(format string, args ...interface{}) {
	console.Debug().Printf(format, args...)
}

func (consoleLogger) Errorf(format string, args ...interface{}) {
	console.Error().Printf(format, args...)
}
```

I propose to add a `Debug` and `Warn` level into the interface and also add some logging throughout the project to remedy this

Something like:
```go
type level string

const (
	// DEBUG Log Level
	DEBUG level = "debug"
	// INFO Log Level (little less log pollution from xDS)
	INFO level = "info"
	// WARN Log Level (show warnigs and potential hazards)
	WARN level = "warn"
	// ERROR Log Level (only log failures)
	ERROR level = "error"
)

// Package log provides a logging interface for use in this library.
package log

// Logger interface for reporting informational and warning messages.
type Logger interface {
	// Debugf logs a formatted debugging message.
	Debugf(format string, args ...interface{})

	// Infof logs a formatted informational message.
	Infof(format string, args ...interface{})

	// Warnf logs a formatted warning message.
	Warnf(format string, args ...interface{})

	// Errorf logs a formatted error message.
	Errorf(format string, args ...interface{})
}
```

@kyessenov @yangminzhu

**Comment by kyessenov** [comment]
Sure. Sounds reasonable. I haven't looked into the state of go logging lately, but it would preferrable to just use some standard logger interface.

**Comment by alecholmez** [comment]
We've integrated https://github.com/rs/zerolog throughout Grey Matter's control plane and it really serves us well and is fast, I wouldn't be opposed to integrating this into go-control-plane, a structured logger would be a nice addition as well.

**Comment by kyessenov** [comment]
Let's not introduce a dependency on rs/zerolog. Some projects are very opinionated about logging, so we don't need to cause a conflict in the library choice. It's quite unfortunate that there is no standard logger interface, but it seems reasonable to define and use the interface above.
