### ISSUE TITLE
Dynamic secrets are getting stuck at warming state 

### ISSUE THREAD

**Issue by budanm** [envoyproxy/go-control-plane#249]
**Description**

When we add additional secrets to snapshot cache than what is referred from the listener/cluster TLS contexts, secrets config in envoy gets stuck into warming state. 

Looking in control plane [code](https://github.com/envoyproxy/go-control-plane/blob/master/pkg/cache/simple.go#L236),  we see that in case of extra resources than asked for, in ads mode, control plane doesn't send any resource of that type. And hence we are seeing the error in envoy client.
 
However, as per the docs from [envoy](https://www.envoyproxy.io/docs/envoy/v1.12.1/api-docs/xds_protocol), in case of extra resources, envoy will silently ignore it. Question is why shouldn't this be also handled in control plane and either send all or send only ones asked for instead of not sending any resource at all.

**Comment by kyessenov** [comment]
ADS mode is just a way to ensure consistency. If you send a partial subset and get a confirmation, then you have to follow-up with the full set to fully push the set. What ADS does is to hold on responding until the whole set of requested. The set of resources that Envoy asks for is eventually consistent, so it takes time for the request to come.

You don't have to use ADS for everything. You can point SDS to another server that just always responds with secrets.

**Comment by budanm** [comment]
Ok , but in this case I am not sending a partial subset , rather I am sending an additional entry in the set .My expectation is that additional entry should be ignored and it should not get stuck at warming state

**Comment by kyessenov** [comment]
Not sure I'm following. Can you list a sequence of request/response pairs in xDS?

**Comment by fxl0206** [comment]
same  question ，"You can point SDS to another server that just always responds with secrets."    ？  it mean that user must  start  another xds server.  is it Reasonable?
