### ISSUE TITLE
[Query] : Consistency check does not cover secrets 

### ISSUE THREAD

**Issue by budanm** [envoyproxy/go-control-plane#253]
Hi

The issue is more of a query. As per the implementation of the snapshot Consistent [method](https://github.com/envoyproxy/go-control-plane/blob/ea341cfe14515bb0a8eeedaa857b8a546dc0d0c8/pkg/cache/snapshot.go#L79), it seems we do not allow any orphan/ unreferenced route configs and we also do not allow any orphan endpoints, which is fair. 

However, we do not perform such checks for secrets. Now secrets can be both referred from listeners ( for filter chain tls contexts ) as well as clusters. 
Are we saying that the snapshot will be consistent if there are orphan secrets? Recently we ran into an issue where we did have orphan secrets in the snapshot and that actually resulted in a warming state for the dynamic secrets and it was stuck there. Any help would be appreciated

**Comment by kyessenov** [comment]
I think we didn't update the consistency check to compute all referenced secrets. 
Secrets are a relatively new feature in xDS.

**Comment by budanm** [comment]
Are you guys planning to introduce secrets as well as part of the consistency check ?
