### ISSUE TITLE
Remove a loaded listener

### ISSUE THREAD

**Issue by hanfubin** [envoyproxy/go-control-plane#256]
How to dynamically delete(or update) a listener(or route) after it is successfully loaded by go-control-plane in envoy

**Comment by alecholmez** [comment]
@hanfubin To achieve this you would need some sort of API on top of your go-control-plane server that would be able to make the change.

go-control-plane is simply a shuttle for configuration to Envoy's. So if it broadcasted listeners out to your nodes, then the only way to modify that configuration would be to do it inside of the go-control-plane snapshot. Many people have built APIs on top of their control-plane implementations for this specific reason.
