### ISSUE TITLE
where is the pb build script?

### ISSUE THREAD

**Issue by maplebeats** [envoyproxy/go-control-plane#263]
We developed some plugins for envoy, I want to compile there pbs config to golang.So I want to refer to the project's compile script, But I can't found any build scripts anymore.I see the pbs update by go-control-plane(CircleCI) , but I can't found the ci config. 
Does anyone know where it is ?

**Comment by kyessenov** [comment]
The tool lives in envoy itself https://github.com/envoyproxy/envoy/blob/master/tools/api/generate_go_protobuf.py

**Comment by maplebeats** [comment]
thanks
