### ISSUE TITLE
Add support for v3 apis

### ISSUE THREAD

**Issue by jyotimahapatra** [envoyproxy/go-control-plane#264]
At Lyft, we are moving a lot of configs into v3. I was wondering if the presence of v3 in server.go is only a matter of implementing it? If so, are there any obvious traps while implementing?

**Comment by kyessenov** [comment]
There shouldn't any problem I think. Envoy internally convers v2->v3 anyways, so it's more efficient to send v3 nowadays. I think doing a pass and changing all the protos to use v3 would work.

**Comment by jyotimahapatra** [comment]
I think at some point this year, all new fields will only be added to v3. So it perhaps makes sense to add v3 support. However, it has to be live in parallel with v2, since v2 will still be supported till v4 comes out. Does that sound correct?

**Comment by kyessenov** [comment]
Right now, all changes to v3 require a corresponding change to v2 I think in envoy repo.
I really don't want to maintain two different versions for v2 and v3. I would prefer to wait for Envoy 1.13 to become wide spread and then make the conversion.

**Comment by jyotimahapatra** [comment]
That makes sense. However, I was wondering how to make the migration from v2 to v3 easy for us. We are using the gcp for handling DiscoveryRequest/Response. Say we want to migrate just the eds to v3 and then cds/rds/lds/rtds and so forth in phases, i don't think it is possible without having v2 and v3 living in parallel. 
Do you think it's worth thinking about this situation? Do you think other users of go-control-plane might also benefit from this?

**Comment by kyessenov** [comment]
It's certainly worth thinking about it. I think it's going to become significantly more important for v3->v4 migration.

**Comment by mattklein123** [comment]
Per my comment in slack I think we need to figure out dual support for v2 -> v3, so let's put some thought into it now? I think our options are really some type of automated conversion or some type of copying. Can we investigate and then discuss?

**Comment by kyessenov** [comment]
This was done.
