### ISSUE TITLE
Move CI from circleci to Azure pipelines

### ISSUE THREAD

**Issue by eapolinario** [envoyproxy/go-control-plane#288]
By moving to azure pipelines we can leverage [envoy's dockerhub account](https://hub.docker.com/u/envoyproxy) as a repository of `go-control-plane` docker images.

**Comment by kyessenov** [comment]
Agree, but I don't have access to azure pipelines. 
@lizan might be able to help.

**Comment by lizan** [comment]
Yeah sure, what image are we trying to publish? I can setup a bare minimum pipelines, or you can also setup GitHub actions, because go-control-plane don't need RBE or self-hosted agents.

**Comment by kyessenov** [comment]
It's using https://github.com/envoyproxy/go-control-plane/blob/master/Dockerfile.ci. Just need regular go tools.
