### ISSUE TITLE
Support passthrough of Envoy DiscoveryResponses

### ISSUE THREAD

**Issue by jessicayuen** [envoyproxy/go-control-plane#299]
In [xds-relay](https://github.com/envoyproxy/xds-relay), we have a use case of relaying DiscoveryResponses received upstream directly to the downstream Envoy clients.

We're utilizing go-control-plane's `CreateWatch` functionality to achieve this passthrough. A problem exists where the returned Discovery Response upstream already contains the marshaled resources. `CreateWatch` expects the responses to be of type [Response](https://github.com/envoyproxy/go-control-plane/blob/v0.9.5/pkg/cache/v2/cache.go#L54-L71) and then converts the response type to type DiscoveryResponse [later in the chain of events](https://github.com/envoyproxy/go-control-plane/blob/v0.9.5/pkg/server/v2/server.go#L143-L181).

We would like to add support to not do a DiscoveryResponse -> gcp.Response -> DiscoveryResponse conversion, and instead add an interface to support a direct passthrough of the final DiscoveryResponse.

Please refer to the discussion here for more details: https://envoyproxy.slack.com/archives/CTULFMN91/p1589474718031700

**Comment by jessicayuen** [comment]
cc @kyessenov - I plan to open a PR to support this. Please let me know your thoughts.

**Comment by jessicayuen** [comment]
Been thinking of ways we can approach this with pros/cons to each. Let me know your thoughts @jyotimahapatra @kyessenov 

1. Adding a new server and interface `PassthroughWatcher`, which contains a single contract `CreateWatch(Request) (value chan discovery.DiscoveryResponse, cancel func())`
- The existing server implementation is tightly coupled with the gcp Cache. This would allow us to add new support without coupling with the current contracts and adding bloat where implementations are not utilizing this new functionality. This would also allow us to create a implementation that doesn't rely on [Fetch](). This approach would involve the most work and require us to support two server types.

2. Adding a `discovery.DiscoveryResponse` variable to the [Response](https://github.com/envoyproxy/go-control-plane/blob/v0.9.5/pkg/cache/v2/cache.go#L54-L71) object.
This one is straightforward in that if this discovery response is set, we simply ignore the resource variables and do not to the conversion of `Response` -> `DiscoveryResponse` during processing. The downsides of this approach is that it creates confusion for those looking at the `Response` struct for why there exists both a DiscoveryResponse and separate resource arrays.

3. Changing type of [marshaledResources](https://github.com/envoyproxy/go-control-plane/blob/v0.9.5/pkg/cache/v2/cache.go#L70) in cache from type `[]byte` to type `any.Any`. This allows us to pass the final marshaled resources of type `any.Any` directly. Downsides are a change to the existing contract, that consumers would have to adapt to on the next pull of go-control-plane. There is also slightly more overhead for the consumer to convert their resources into type `any.Any`. xds-relay will also have some redundancy / slight performance overhead of unwrapping the `DiscoveryResponse` to pull out the resources, passing it to go-control-plane in the `Response` struct, and then have it wrapped up again.

**Comment by jyotima** [comment]
I'm somewhat leaning towards approach 3. The marshaledResources today is somewhat complicated and requires the user to perform the marshal(We perform that in EnvoyManager). If we could hide the logic behind a setting and let the server perform and populate marshaledReources, it should take care of hiding the complexity and inherent redundancy.

**Comment by jyotimahapatra** [comment]
I'm somewhat leaning towards approach 3. The marshaledResources today is somewhat complicated and requires the user to perform the marshal(We perform that in EnvoyManager). If we could hide the logic behind a setting and let the server perform and populate marshaledReources, it should take care of hiding the complexity and inherent redundancy.

**Comment by eapolinario** [comment]
A few things to consider in approach 3:
-  marshaledResources is a relatively new one (it happened [~6 months ago](https://github.com/envoyproxy/go-control-plane/pull/240/)). That means that not many clients should be using it. I know it's hard to gauge users in the wild, but we can alleviate this by having a big bold message in the release notes.
- can we run a quick test to show how big of a perf impact that extra overhead will be?

Approach 3 has the benefit of clarifying gcp code while at the same time enabling our scenario in xds-relay. I say we go with it unless the perf impact is ridiculously large.

**Comment by jessicayuen** [comment]
I think that approach 1 may be the longer term solution if we want better flexibility around the interface definitions. Approach 3 makes sense for the interim. I will go with that implementation to unblock ourselves. 

> The marshaledResources today is somewhat complicated and requires the user to perform the marshal(We perform that in EnvoyManager).

If we change it to type `any.Any`, the user would have to do more marshaling actually, because they'd have to first convert resources to type `[]byte` and then apply the `any.Any` wrapper, as seen [here](https://github.com/envoyproxy/go-control-plane/blob/v0.9.5/pkg/server/v2/server.go#L169-L172).

> marshaledResources is a relatively new one (it happened ~6 months ago). That means that not many clients should be using it. I know it's hard to gauge users in the wild, but we can alleviate this by having a big bold message in the release notes.

I agree that this would not be a main concern. When users pull in the dependency, their codebase would not compile anyhow and the errors would have to be adjusted before they can complete the dependency update. As opposed to an unsurfaced behavior change deeper in the gcp implementation.

> can we run a quick test to show how big of a perf impact that extra overhead will be?

The perf hit should not be huge since we're primarily reassigning variables to different structs vs. re-marshaling. There are, however, some code smells of why we're going from DiscoveryResponse -> Response -> DiscoveryResponse.

But let's go with this approach for now and revisit 1 as needs arise.

**Comment by jyotimahapatra** [comment]
> If we change it to type any.Any, the user would have to do more marshaling actually, because they'd have to first convert resources to type []byte and then apply the any.Any wrapper,

We need to re-purpose MarshaledResources such that the extra logic of conversion is not the user's responsibility. The conversion should happen automatically based on a setting/flag.

**Comment by jessicayuen** [comment]
To make sure I understand correctly, what are the users passing to the Response struct in that scenario?

**Comment by jyotimahapatra** [comment]
Some more elaborate thinking:
1. The responsibility of putting the `resp.ResourceMarshaled` and `resp.MarshaledResources` should not be user's responsibility. It should be a default mechanism and should happen by default after the resource is [marshalled](https://github.com/envoyproxy/go-control-plane/blob/v0.9.5/pkg/server/v2/server.go#L165). We can make the fields unexported and the field need not be exposed to the user at all.
2.  Since we are thinking resource transformations in xds-relay in the future, we need a setting at the cache level(probably based on typeurl) to signify whether the cache is passthrough or needs marshalling and use the setting [here](https://github.com/envoyproxy/go-control-plane/blob/v0.9.5/pkg/server/v2/server.go#L158) to branch between marshalling or not. This part can be made an interface as well like you mentioned.
3.

**Comment by jessicayuen** [comment]
> The responsibility of putting the resp.ResourceMarshaled and resp.MarshaledResources should not be user's responsibility. It should be a default mechanism and should happen by default after the resource is marshalled. We can make the fields unexported and the field need not be exposed to the user at all.

I completely agree that those resources can be abstracted away and shouldn't be a responsibility for the end user to manage cache layers. There's definitely optimizations that can be done here. It's a tangent area of work though, and doesn't support the use case xds-relay requires, which is a passthrough of the finalized marshaled DiscoveryResponse to the GCP server.

Ultimately we need a way to pass the DiscoveryResponse downstream. Since the contract is `CreateWatch(Request) (value chan Response, cancel func())`, and the current server being [heavily reliant](https://github.com/envoyproxy/go-control-plane/blob/v0.9.5/pkg/server/v2/server.go#L77) on implementations that obey this contract, there is only so much we can do (mainly approaches 2 and 3). A separate server will give us the flexibility to adapt to a new interface. Mainly why I like approach 1. Approach 3 is a simple solution to move forward for the short term though.

**Comment by jyotimahapatra** [comment]
I think the concept of whether a resource is passthrough or not is more granular than the whole server. Imagine a usecase in the future where xds relay is used directly via admin endpoint or pluggable transformations to serve cds and upstream origin server to serve eds. That scenario will need xds relay to be aware of both mechanisms. Starting 2 servers to manage different scenarios will be an overkill imo. That's the reason behind me being hesitant about changing server interface.

**Comment by jessicayuen** [comment]
I don't think we'd need two servers in that scenario. xds-relay would only ever use the new server. The transformations would happen at the xds-relay later, and any conversions to the final DiscoveryResponse would occur in xds-relay (rather than gcp). Something that needs greater design though. 

How about we go with approach 3 for now? Just converting the marshaledResources from type `[]byte` to `any.Any`? That requires minimal changes to the current contract and will also support the MVP needs of xds-relay.

**Comment by jyotimahapatra** [comment]
Yeah let's go with that for now, but would you be ok with making the change like this https://github.com/envoyproxy/go-control-plane/pull/300/files to make sure we remove the user's responsibility of creating marshalled resource.

**Comment by jessicayuen** [comment]
That looks reasonable @jyotimahapatra, although if we're going with a different `PassthroughResponse` struct, I wonder whether we should just store the `DiscoveryResponse` rather than type `any.Any`.

**Comment by jessicayuen** [comment]
Also since you already have the PR, I'm fine with you taking it out of experimental mode and just iterating on that. Let me know.

**Comment by jyotimahapatra** [comment]
Sounds good. I think I can quickly write the tests and put it out for review

**Comment by jessicayuen** [comment]
Implemented in #300
