### ISSUE TITLE
Have the ability to have different TypeUrl from Discovery Request vs Discovery Response

### ISSUE THREAD

**Issue by lita** [envoyproxy/go-control-plane#303]
Currently, go-control-plane doesn't provide a way for us to send v3 configuration through the v2 protocol, as supported by envoy for a migration.

For Fetch, [it always sets the DiscoveryRequest TypeUrl](https://github.com/envoyproxy/go-control-plane/blob/bd7e4474d763c1ba0b91757b3ff069d72f211fed/pkg/server/v2/server.go#L429).

For Streaming, it always uses the[ v2 resources when using the v2/cache.go module](https://github.com/envoyproxy/go-control-plane/blob/bd7e4474d763c1ba0b91757b3ff069d72f211fed/pkg/server/v2/server.go#L235).

In order to support the v2->v3 migration, we will need to add functionality here to allow the TypeUrl to be changed. It's not clear to me if the[ passthrough work will handle this or not](https://github.com/envoyproxy/go-control-plane/pull/300/files#diff-559e68cd870b75c9dbc9c282d7592466R122), since it is still using the request TypeUrl.

**Comment by jyotimahapatra** [comment]
I don't think envoy accepts v3 response in return for a v2 request, based on the observation [here](https://github.com/envoyproxy/envoy/issues/10776#issuecomment-615356172).

**Comment by lita** [comment]
After talking with @jessicayuen, it looks like the [Passthrough struct takes the raw discovery proto](https://github.com/envoyproxy/go-control-plane/pull/300/files#diff-559e68cd870b75c9dbc9c282d7592466R87).

**Comment by lita** [comment]
@jyotima I believe Envoy added code to do the v2 -> v3 conversion since the last time you did that test.

**Comment by jyotimahapatra** [comment]
@lita That's possible, but i saw that the issue is still open and not linked to any PR. Worth retesting it again to check if this is solved.

**Comment by jyotimahapatra** [comment]
In order to perform migration, go-control-plane enables registering the v3 endpoint. Although the cache management will require more code until https://github.com/envoyproxy/envoy/issues/10776 is done.

**Comment by lita** [comment]
I think fully mixed is not supported. But sending v3 resources over v2 transport is supported. 

https://github.com/envoyproxy/envoy/issues/10776#issuecomment-621220211

https://www.envoyproxy.io/docs/envoy/latest/faq/api/envoy_v3

**Comment by jyotima** [comment]
That is true. The grpc endpoints are chosen based on [type_url](https://github.com/envoyproxy/envoy/blob/master/source/common/config/grpc_mux_impl.cc#L61) , based on [resource_api_version](https://github.com/envoyproxy/envoy/blob/master/source/common/config/type_to_endpoint.cc#L30-L46) .
The transport_api_version is only really used [here](https://github.com/envoyproxy/envoy/blob/master/source/common/config/grpc_mux_impl.cc#L60) to scrub deprecated fields.

**Comment by jyotimahapatra** [comment]
That is true. The grpc endpoints are chosen based on [type_url](https://github.com/envoyproxy/envoy/blob/master/source/common/config/grpc_mux_impl.cc#L61) , based on [resource_api_version](https://github.com/envoyproxy/envoy/blob/master/source/common/config/type_to_endpoint.cc#L30-L46) .
The transport_api_version is only really used [here](https://github.com/envoyproxy/envoy/blob/master/source/common/config/grpc_mux_impl.cc#L60) to scrub deprecated fields.
