### ISSUE TITLE
Add VirtualHostDiscoveryService support

### ISSUE THREAD

**Issue by jpeach** [envoyproxy/go-control-plane#310]
Looks like there's no support for VirtualHostDiscoveryService.

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/dynamic_configuration.html#vhds

**Comment by kyessenov** [comment]
I think this needs incremental xDS.

**Comment by jpeach** [comment]
> On Aug 14, 2020, at 3:09 AM, Kuat <notifications@github.com> wrote:
> 
> ﻿
> I think this needs incremental xDS.
> 
Is that a xDS protocol constraint, or just the way Envoy implements it?

**Comment by kyessenov** [comment]
I think that's how Envoy implements it, but I may be wrong. I think both SRDS and VHDS use incremental.

**Comment by artificial-aidan** [comment]
This is still a nice to have.
