### ISSUE TITLE
Master Branch Failed State?

### ISSUE THREAD

**Issue by JesseObrien** [envoyproxy/go-control-plane#313]
The master branch on this repo being in a failed build state is causing problems in uber's prototool. https://github.com/uber/prototool/issues/562

Is there anything I can do to help correct the failed build?

**Comment by JesseObrien** [comment]
I see there's https://github.com/envoyproxy/go-control-plane/pull/312 to address it.

**Comment by JesseObrien** [comment]
This is happening again today because of e2103857d09deb84008e73de3e4ce1bd87775590

**Comment by kyessenov** [comment]
Fix is in https://github.com/envoyproxy/envoy/pull/11627

**Comment by kyessenov** [comment]
Should be fixed now.
