### ISSUE TITLE
How to use the go control plane

### ISSUE THREAD

**Issue by shivam009** [envoyproxy/go-control-plane#328]
I am trying to use the go control plane with Envoy, but due to lack of documentation i am finding it difficult to run the go control place as management server, is there any documentation available using which i can make changes in the go control plane and run it to use it according to me.

**Comment by acnodal-tc** [comment]
I'm also a control-plane newbie and I've found the integration tests to be a great example.  Run "./build/run_docker.sh make integration" to get started, and look in build/integration.sh and pkg/test/main/main.go to see how it works.

**Comment by alecholmez** [comment]
@shivam009 @acnodal-tc is right the integration tests are a great place to start. I can try and write up some docs on writing an example management server from go-control-plane. It was more or less designed to be a reusable server that people can important and get up and running quickly with such as the README suggests. Are you referring to how to use it as the gRPC server or the sub packages such as the snapshot cache or everything?

**Comment by acnodal-tc** [comment]
I've submitted #330 which might help.

**Comment by shivam009** [comment]
Thanks for responsing.
@acnodal-tc @alecholmez 
I have few questions regarding using the control plane :
1) In the main.go i see you are taking NodeID as input, i don't understand this. I might have a management server(control plane) from which multiple envoy instances would be fetching data. So now How can i pass the NodeID of these Envoy instances before hand to generate the snapshot. There should be a mechanism that whenever a new node creates a request from the management server, then we should fetch the Node id and create a snapshot for that node and setSnapshot in our cache. 
2) I am just trying to implement Route discovery service and everything else will be static, hence i tries to run the control plane as RDS, now when i am calling streamRoutes i am able to get the routes from control plane (provided there was a snapshot for the nodeid), but now i want whenever there is a change in rule so lets say whenever there is a change in rule i do a setSnapshot for all the nodes, then how would server stream new routes to all the active streams? (Inside server.go, inside function process, i understand there is var values watches, now i am not sure how to put value to values.routes whenever a route is updated

**Comment by acnodal-tc** [comment]
1. I haven't looked at the code enough to know whether there's a callback mechanism to do what you want.  At the moment the snapshots are predefined.  You add a snapshot to the cache ahead of time, and when Envoy requests configuration it provides a NodeID which tells the xDS server which snapshot to serve.
1. IIUC you would use the snapshot's version for that - bump the version and the xDS server will serve the new version.

**Comment by shivam009** [comment]
@acnodal-tc  Thanks for responding, 
1) Is there a document i can refer to know more about callbacks, because callbacks are one think i am not able to understand fully from the code.
2) I tried doing the same, i bumped the version and did setSnapshot for the node, but there was no response from sDS server on the stream to send the latest rules, that is why i wanted to know how to do that. One way of doing that i saw was to create a watch (just like when version is same for any request we create an open watch, so should i always have an open watch for all my streams to serve this

**Comment by acnodal-tc** [comment]
1. I don't know if such a mechanism exists, you'd have to dive into the code to see.
2. When you say "no response" do you mean that the xDS server continued to serve the previous snapshot?

**Comment by alecholmez** [comment]
@shivam009 my initial docs PR was just merged, can we close this?

**Comment by velcrine** [comment]
> @shivam009 my initial docs PR was just merged, can we close this?

Pls dont. The below question's 1st point needs to be answered.


> Thanks for responsing.
> @acnodal-tc @alecholmez
> I have few questions regarding using the control plane :
> 
>     1. In the main.go i see you are taking NodeID as input, i don't understand this. I might have a management server(control plane) from which multiple envoy instances would be fetching data. So now How can i pass the NodeID of these Envoy instances before hand to generate the snapshot. There should be a mechanism that whenever a new node creates a request from the management server, then we should fetch the Node id and create a snapshot for that node and setSnapshot in our cache.

**Comment by velcrine** [comment]
@shivam009  can you please clarify how u worked around with Pointer 1 of yours, that NodeId needs to be set beforehand, and thus dynamic NodeId will not work.

**Comment by velcrine** [comment]
got to know about callbacks. They work perfectly.
