### ISSUE TITLE
StreamSecrets gRPC  error usig SDS service

### ISSUE THREAD

**Issue by tessykt** [envoyproxy/go-control-plane#348]
Hello,

I have beeing trying to send the certificates towards the envoys via SDS.
I am using the latest hash of master branch of go-control-plane repo.
Envoy produces the following logs:

[warning][config][bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] StreamSecrets gRPC config stream closed: 14, no healthy upstream
[debug][config][source/common/config/grpc_subscription_impl.cc:88] gRPC update for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret failed
[warning][config][bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:54] Unable to establish new stream
[debug][config][source/common/config/grpc_subscription_impl.cc:88] gRPC update for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret failed
[debug][init][source/common/init/target_impl.cc:15] init manager Cluster nrf-agent initializing target SdsApi Validationcontext
[debug][config][source/common/config/grpc_mux_impl.cc:75] gRPC mux addWatch for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret
[debug][config][source/common/config/grpc_mux_impl.cc:32] No stream available to sendDiscoveryRequest for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret
[debug][config][bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:47] Establishing new gRPC bidi stream for rpc StreamSecrets(stream .envoy.service.discovery.v3.DiscoveryRequest) returns (stream .envoy.service.discovery.v3.DiscoveryResponse);

[debug][router][source/common/router/router.cc:477] [C0][S14949892820424518695] cluster 'sds_server_mtls' match for URL '/envoy.service.secret.v3.SecretDiscoveryService/StreamSecrets'
[debug][upstream][source/common/upstream/cluster_manager_impl.cc:1235] no healthy host for HTTP connection pool
[debug][http][source/common/http/async_client_impl.cc:96] async http request response headers (end_stream=true):
**':status', '200'
'content-type', 'application/grpc'
'grpc-status', '14'**
'grpc-message', 'no healthy upstream'

[warning][config][bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] **StreamSecrets gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection termination**"

I have enabled only the registration of SecretDiscoveryService

Can you please help?
thank you in advance!

**Comment by kyessenov** [comment]
This looks like a generic error with an upstream. There is nothing special with SDS as opposed to other xDS. You just need to register "v3" stubs like done here https://github.com/envoyproxy/go-control-plane/blob/master/pkg/test/v3/register.go#L46.

**Comment by mbana** [comment]
@tessykt did you resolve this issue?

**Comment by tessykt** [comment]
it seems that this was the output in case that we have the sds part in place and the envoys have been configured wrongly to communicate with v2 and not v3 messages.

**Comment by mbana** [comment]
> it seems that this was the output in case that we have the sds part in place and the envoys have been configured wrongly to communicate with v2 and not v3 messages.

How did you figure this out? Which part of the code is doing this exactly?
