### ISSUE TITLE
v3’s EndpointDiscoveryService is discovered with v2 resulting in "unknown service envoy.api.v2.EndpointDiscoveryService" error

### ISSUE THREAD

**Issue by irinagordei** [envoyproxy/go-control-plane#356]
Envoy: v1.15.0
go-control-palne: v0.9.5

My intention is to fully transition to v3. I have the xDS server registered with v3 xDS APIs, and the bootstrap has dynamic resources’ **resource_api_version** and **transport_api_version** point to v3 where applicable.

I still see that my static resources (listeners, xDS cluster) in bootstrap are parsed as v2. The Envoy’s /config_dump shows them as v2:
```
cluster": {
      "@type": "type.googleapis.com/envoy.api.v2.Cluster",
      "name": "xds_cluster",
      "type": "STATIC",
. . .
"listener": {
      "@type": "type.googleapis.com/envoy.api.v2.Listener",
      "name": "egress-listener",  
```

Given that routes, clusters and endpoints are intended to be provisioned via dynamic xDS, 
```
dynamic_resources:
  cds_config:
    resource_api_version: V3
    api_config_source:
      api_type: GRPC
      transport_api_version: V3
      grpc_services:
        envoy_grpc:
          cluster_name: xds_cluster
. . . 
rds:
  route_config_name: ingress-route
  config_source:
    resource_api_version: v3
    api_config_source:
      api_type: GRPC
      transport_api_version: v3
      grpc_services:
        envoy_grpc:
          cluster_name: xds_cluster
```
I’m only able to see gRPC streams opened for v3 routes and v3 clusters but **not v3 endpoints**. Instead, a v2 DiscoveryRequest is sent:
```
[debug][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:48] Establishing new gRPC bidi stream for rpc StreamEndpoints(stream .envoy.api.v2.DiscoveryRequest) returns (stream .envoy.api.v2.DiscoveryResponse);
[debug][router] [source/common/router/router.cc:426] [C0][S10598310115315123671] cluster 'xds_cluster' match for URL '/envoy.api.v2.EndpointDiscoveryService/StreamEndpoints'
. . .
[trace][config] [source/common/config/grpc_mux_impl.cc:64] Sending DiscoveryRequest for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment: node {
. . .
resource_names: "service A"
type_url: "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
...
[warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:93] StreamEndpoints gRPC config stream closed: 12, unknown service envoy.api.v2.EndpointDiscoveryService
```
Could you point to what is missing in the new configuration? My bootstrap resembles [this configuration](https://www.envoyproxy.io/docs/envoy/v1.15.0/configuration/overview/examples#dynamic) with only static listeners.

**Comment by alecholmez** [comment]
Here's a sample configuration that could potentially help you:
https://github.com/envoyproxy/go-control-plane/blob/master/sample/bootstrap-xdsv3.yaml

I don't know if I've ever seen that before, let me know if that config is of any use
