### ISSUE TITLE
Synchronize releases with Envoy?

### ISSUE THREAD

**Issue by numerodix** [envoyproxy/go-control-plane#365]
The last go-control-plane release 0.9.7 was on 2020-10-02, which is a bit "unlucky" because Envoy 1.16 was released on 2020-10-09, just seven days later. This might mean that users of go-control-plane might need to wait a couple of months to consume new protobuf types from Envoy 1.16, given that releases of go-control-plane are spaced 2-3 months apart. 

Would it be possible to try to synchronize releases of go-control-plane with Envoy, such that we get a new release of go-control-plane a week or two after the release of an Envoy major version?

**Comment by kyessenov** [comment]
The APIs at head are usually stable so you can always just go get @ release SHA. Go versions don't align well with Envoy versions (some protos do make incompatible changes occassionally in alpha land), so I'm not sure how to make it more obvious which version/SHA to pick. Maybe we need some sort of tag from Envoy version that's not a version in go sense?
