### ISSUE TITLE
Cache Comparison

### ISSUE THREAD

**Issue by gregdurham** [envoyproxy/go-control-plane#37]
Would it make sense to add a comparison method in the simple cache, where you can send an old snapshot and compare it to what you want the snapshot to be, comparing everything except version? 

If using a timer based updater (naive approach), this would allow us to not cause proxies to update unless changes occur. There likely is a better approach to this.

**Comment by kyessenov** [comment]
Sure, that would be useful functionality. We might need to add "equals" methods on the relevant protobuf generated types, I think (and those are known to have problems with `map` fields). I'm playing with gogoprotobuf which has some capability to auto-generated "equals" in many cases.
In case you're wondering, Envoy actually does some diffing internally, so the cost of re-sending a snapshot is purely on the wire and in computing the diff, I believe.

The alternative is to delegate this logic to the producer of the snapshot. Producer is likely to take data sources from which it derives the desired snapshot for the proxies in some deterministic fashion. It might be sufficient to only send snapshots if a change in the input is detected.

In the future, we will have a delta-aware xDS protocol. In that case, the producer might need to produce diffs (add objects, remove objects, modify objects).

**Comment by gregdurham** [comment]
Thanks @kyessenov I think for a first iteration approach, I will start with the index incrementing, hoping that envoy doesn't reload unless a change occurs. My next approach, likely will be to control the snapshot from the producer side.

**Comment by kyessenov** [comment]
Sounds good to me. I've just seeded all core structs with auto-generated "Equals()" methods in my upcoming data-plane-api upgrade PR. That should make it simple to compare snapshots prior to serializing them.
