### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by easwars** [envoyproxy/go-control-plane#371]
Could we please have a new release?

cncf/udpa repo made some breaking changes in this commit: https://github.com/cncf/udpa/commit/82be644d481c4a40574a9ccc53de3047c8d661d0

And this has been pulled into go-control-plane as part of: https://github.com/envoyproxy/go-control-plane/commit/06aa925ade771a721b75eabecffe21b2b0b28352

gRPC-Go has a dependency on go-control-plane and cncf/udpa, and we need to move up to the latest commit of the latter.

Also, is there is any plan of doing a v1.x for go-control-plane? If not for the whole repo, it would be very beneficial if a v1 release is done at least for a submodule hosting the `pb.go`s.

Thanks.

**Comment by easwars** [comment]
@dfawley @menghanl

**Comment by kyessenov** [comment]
@easwars Sure, I can make a release. I've been waiting for outcome of a discussion (https://github.com/envoyproxy/go-control-plane/pull/369) due to some internal changes. @jyotimahapatra, do you think it's safe to ship the API change in a release.

I'm hesitant about v1 because of mis-alignment with xDS versioning. There is an expectation of backwards compatibility past 1.0, and the breaking changes like the one in cncf/udpa is not acceptable in a minor update. I'm flexible on this, so if there is enough demand, it's not a big deal to tag a v1.

**Comment by easwars** [comment]
Thanks @kyessenov 

Could we also please make sure that https://github.com/envoyproxy/go-control-plane/pull/372 gets in before tagging a new release.

I also filed an issue with cncf/udpa asking for a v1: https://github.com/cncf/udpa/issues/42.

**Comment by jyotimahapatra** [comment]
@kyessenov im performing the test today and will let you know by end of day

**Comment by jyotimahapatra** [comment]
@kyessenov i did some tests and looks like there is a bug lurking somewhere. I [made sure](https://github.com/envoyproxy/xds-relay/pull/205/files) to cleanup state after every xds response sent. However, we are getting into a situation where the channel gets into a blocked state. 
<img width="2493" alt="Screen Shot 2020-12-01 at 2 02 25 PM" src="https://user-images.githubusercontent.com/49211422/100802212-ece2af00-33dd-11eb-9835-fc5cae4aa93f.png">

**Comment by jyotimahapatra** [comment]
Given the complexity of the change and the difficulty in troubleshooting, i suggest reverting the draining change and then perform a release. 
I'm not able to vet the change in our staging environment even after multiple attempts.

**Comment by easwars** [comment]
Any update on the release? @kyessenov 
Thanks.

**Comment by cretz** [comment]
Why closed without waiting for an update?

**Comment by easwars** [comment]
Release v0.9.8 was made after this issue was filed.
