### ISSUE TITLE
Provide parsing and reading capabilities of admin interface

### ISSUE THREAD

**Issue by storyicon** [envoyproxy/go-control-plane#381]
Envoy's admin page provides some interfaces to access envoy runtime information, such as:
```
/clusters?format=json
/config_dump
```
In some cases we may need to parse them out.
If there is a public SDK, there is no need for everyone to do the same thing over and over again.
Do you have any intention to do this?

**Comment by kyessenov** [comment]
I think it's effectively https://www.envoyproxy.io/docs/envoy/latest/api-v3/admin/v3/config_dump.proto proto. You can use standard JSON->proto conversion.

**Comment by storyicon** [comment]
thanks @kyessenov , I might be thinking more than just the structure definition.... You know, once there is a api, people want to have a sdk... You may think it is unnecessary, but it seems that go-control-plane is currently the most suitable place to do this. Of course, it's just a small thing.

**Comment by kyessenov** [comment]
It sounds reasonable, but it's an OSS project, so contributions are welcome
:)

**Comment by alecholmez** [comment]
@storyicon do you think this should go here or potentially another project? This is more of a focused control-plane implementation and that's more along the lines of SDK utility. 

What about another OSS project which would be focused on consuming Envoy produced data?
