### ISSUE TITLE
Configuring additional discovery services

### ISSUE THREAD

**Issue by praminda** [envoyproxy/go-control-plane#384]
Hi team,
We have a requirement to add additional discovery services to go-control-plane. Is it possible to attach/register a new discovery service externally without modifying go-control-plane project sources?

**Scenario:**
We are implementing a separate filter chain (implemented in java) for envoy using ext authz filter. For that filter chain we need to implement a separate set of xds services, So it can talk with our go-control-plane based control-plane implementation to get the updated configs/events/resources specific to filterchain.
Ex: this filterchain needs to get its runtime configurations using a new xds service.

So, if we are using go-control-plane to implement our control plane, can we plug in some additional xds services to existing xds protocol implementation of go-control-plane project?
If this is not supported right now is there any plans to support third party xds services? or is there any other way to get xds protocol based solution working without re implementing what go-control-plane has already implemented?

**Comment by Rajith90** [comment]
If this is a valid feature addition, we can contribute to this feature

**Comment by praminda** [comment]
We have implemented this behavior following [kuma](https://github.com/kumahq/kuma/tree/master/pkg/mads) discovery service implementation. That gave us the expected flexibility of adding additional xds services based on envoy implementation.
Thanks.
