### ISSUE TITLE
nonce does NOT survive across xDS stream restarts

### ISSUE THREAD

**Issue by markdroth** [envoyproxy/go-control-plane#388]
I don't know the go-control-plane code well enough to know what it's actually doing here, but I noticed the following comment:

https://github.com/envoyproxy/go-control-plane/blob/31f9241a16e627ba7696bed59a6353c95412ddb5/pkg/server/sotw/v2/server.go#L287

This is inaccurate; the system version may can be reused across xDS streams, but the nonce cannot.  I am clarifying this in the xDS spec in envoyproxy/envoy#14841.

I'm not sure if there's actually a bug here or if this is just a misleading comment, but I figured I'd file this issue to point it out, so that someone who is familiar with this code can figure it out.

**Comment by kyessenov** [comment]
I think "stream" here means multi-plexed xDS over ADS. Nonces are not persisted between gRPC streams.
