### ISSUE TITLE
External Auth Question

### ISSUE THREAD

**Issue by kenjones-cisco** [envoyproxy/go-control-plane#392]
When Envoy calls `Check` (https://github.com/envoyproxy/go-control-plane/blob/main/envoy/service/auth/v3/external_auth.pb.go#L595) are we guaranteed that a fresh context is passed for every request?

After implementing the interface for my specific External Authorization service, I am getting context canceled after less than `100ms` even though I have configured the timeout to actually be `15s`.

Before continuing to investigate why I'm seeing these premature context cancellations, I just want to make sure a fresh context is provided for every single request.

**Comment by kyessenov** [comment]
Which context are we talking about? `context.Context` is something that gRPC provides, so it's probably some deadline configuration.
