### ISSUE TITLE
Future of V2 handling

### ISSUE THREAD

**Issue by snowp** [envoyproxy/go-control-plane#394]
Currently we manage both V2 and V3 code by copying the V2 code and replacing import paths for V3. This works well when the feature set of V2 and V3 are identical, but becomes a pain to manage as V3 only features are added. What should the long term plan for V2/V3 handling be? 

Should we stop supporting V2 at some point?
Should we stop autogenerating V3 and let the two versions diverge?
Should we refactor the codebase to require less duplication, removing the need for autogenerating a copy for V3?

@kyessenov in case you have thoughts here

**Comment by snowp** [comment]
Another problem with supporting V2 is that it means that running the integration tests against a newer Envoy will fail as it now rejects V2 configs by default. If we want to maintain backwards compat for V2 this would likely complicate the integration test setup required

**Comment by kyessenov** [comment]
I think it's fair to remove v2 once Envoy removes v2 code path since there's been ample time to migrate. I don't think it's worth keeping v2 here when that happens.
