### ISSUE TITLE
Upgrade protoc-gen-go-grpc used for generating `.pb.go`s

### ISSUE THREAD

**Issue by menghanl** [envoyproxy/go-control-plane#403]
The `.pb.go`s are generated using old versions of codegen.

Some noticeable differences:
1. messages and services are in the same file, e.g. [v3/csds.pb.go](https://github.com/envoyproxy/go-control-plane/blob/061ab3afe6b87f9308bcfbd759099dc8340f6e3a/envoy/service/status/v3/csds.pb.go#L824) has messages and services
    - see [helloworld](https://github.com/grpc/grpc-go/tree/master/examples/helloworld/helloworld) where they are separated
2. The `RegisterService()` function still takes `*grpc.Server`, not `grpc.ServiceRegistrar`
	- see [helloworld](https://github.com/grpc/grpc-go/blob/de3c78e4f1f16ca8e7f8fed6d12dcf3e1de337c1/examples/helloworld/helloworld/helloworld_grpc.pb.go#L67) for the updated version

Where are versions of `protoc-gen-go` and `protoc-gen-go-grpc` configured?
Can we update to the newer versions? Thanks!

**Comment by menghanl** [comment]
@kyessenov Do you know where the script to generate `pb.go` files is kept?
If you point me to the script, I can make the changes. Thanks.

**Comment by kyessenov** [comment]
@menghanl sorry about the delay. The script is located in envoy repository https://github.com/envoyproxy/envoy/blob/main/tools/api/generate_go_protobuf.py. We probably need to bump bazel rules for golang to get newer plugins.

**Comment by menghanl** [comment]
It seems this cannot be done until `rules_go` adds support for the new code generators: https://github.com/bazelbuild/rules_go/issues/2522

**Comment by phlax** [comment]
i reopened this and added nostale before realizing it wasnt in the envoy main repo - im guessing it probably does want to stay open tho

**Comment by menghanl** [comment]
Why is this issue closed? Looking at the code, it doesn't seem to be fixed?
If it's fixed, can you link the PR? Thanks

**Comment by alecholmez** [comment]
@menghanl The issue was not fixed but the issue was stale and it requires upgrades it a few repos outside of go-control-plane. Envoy's repo would be a better place for this as well as `rules_go`
