### ISSUE TITLE
Open-telemetry proto import problem

### ISSUE THREAD

**Issue by biefy** [envoyproxy/go-control-plane#407]
Data plane API now has a reference to open-telemetry protos. However, go-control-plane API does not reference these new protos when generating go code.  Import of `logs` package is not correctly recognized.  See https://github.com/envoyproxy/go-control-plane/blob/main/envoy/extensions/access_loggers/open_telemetry/v3alpha/logs_service.pb.go#L16

```
package envoy_extensions_access_loggers_open_telemetry_v3alpha

import (
	_ "github.com/cncf/xds/go/udpa/annotations"
	v3 "github.com/envoyproxy/go-control-plane/envoy/extensions/access_loggers/grpc/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	logs "logs"
	reflect "reflect"
	sync "sync"
)
```
This needs to be fixed.  Otherwise, control planes using go-control-plane have no choice but to ignore this package.

**Comment by snowp** [comment]
Should be resolved now, can you verify?

**Comment by biefy** [comment]
The problem is gone.  Thanks @snowp for the fix.
