### ISSUE TITLE
Example is broken

### ISSUE THREAD

**Issue by phlax** [envoyproxy/go-control-plane#419]
the Envoy ci runs the following command:

```
bin/example -debug
```

which throws the following error:

```
internal/example/resource.go:28:2: no required module provides package github.com/envoyproxy/go-control-plane/pkg/cache/v3; to add it:
	go get github.com/envoyproxy/go-control-plane/pkg/cache/v3
internal/example/resource.go:29:2: no required module provides package github.com/envoyproxy/go-control-plane/pkg/resource/v3; to add it:
	go get github.com/envoyproxy/go-control-plane/pkg/resource/v3
make: *** [Makefile:64: bin/example] Error 1

```

envoy ci can be seen here https://dev.azure.com/cncf/envoy/_build/results?buildId=71451&view=logs&j=f1a49366-51c0-540f-0294-f73c2bb311a9&t=7fd036c9-61ec-5b59-3645-e90950dc67a6&l=3053

this has broken the Envoy main build

**Comment by mattklein123** [comment]
Oops. @snowp @alecholmez I think we need to retain the old v3 package paths so we don't break everyone's build? If we can't fix quickly can we revert the v2 removal?

**Comment by alecholmez** [comment]
Oh whoops, I’ll parse through the examples and see if I can fix that.

**Comment by phlax** [comment]
im wondering if/how we can add some kinda deprecation routine before actually removing for good

**Comment by snowp** [comment]
Doing a deprecation cycle is a bit tricky since we don't have version releases really (1.0.0 not yet cut). I think reverting everything back to using the v3 package name has low cost, so I wouldn't be opposed to that. The other options IMO are to let downstream builds break or to start doing some kind of proper versioning.

**Comment by phlax** [comment]
mho is dont break without warning - the fix is not obvious (at least not if you are not a go expert)

for anyone reading this the fix is to remove the `v3` suffix from go-control-plane imports

**Comment by mattklein123** [comment]
Let's just revert the package rename. I don't see any reason to break anyone for this.

**Comment by alecholmez** [comment]
@mattklein123 @snowp would you like me to just go ahead and add back the v3 package path? IMO the break this is causing is a really simple fix, just a matter of removing a few characters from an import path but I can go ahead and bring that back in if we'd like.

**Comment by phlax** [comment]
its only a simple fix if you know what changed - if not you need to read the source/commits to figure what changed

**Comment by mattklein123** [comment]
Imo I would switch it back. We can revert the envoy side fix when it lands. I just don't think it's worth the build break.

**Comment by alecholmez** [comment]
Sounds good, just opened the PR to do so

**Comment by alecholmez** [comment]
@phlax has this been resolved? The import paths were reverted

**Comment by phlax** [comment]
afaict yes - Envoy post-submit seems happy
