### ISSUE TITLE
snapshot cache does not respond with resources

### ISSUE THREAD

**Issue by easwars** [envoyproxy/go-control-plane#426]
gRPC-Go uses the go-control-plane server as our management server in some of our e2e tests. And as part of one of the tests, I was doing the following:
- Spun up a go-control-plane server.
- Added some resources to be used on the gRPC-client (listener, route config, cluster, endpoints) and gRPC-server (inbound listener) as part of a new snapshot into the cache.
- started the gRPC-server. This sends a request for the inbound listener resource.
- create `gRPC-client-1` (which does not request xDS resources) and expect RPCs to fail with a specific error code.
- then create a `gRPC-client-2` (which actually requests for the xDS resources we added to the cache), and expect it to make a successful RPC to the server.

What I found was that the gRPC-server was not receiving the inbound listener resource it was expecting to receive. This was happening because `gRPC-client-2` had not yet been created at this point, and because of the check [here](https://github.com/envoyproxy/go-control-plane/blob/cde9fa27f1d43c1a4555261145f18b53414731b0/pkg/cache/v3/simple.go#L329), the snapshot cache was suppressing the resource being sent out (because not everything in the snapshot was requested).

I also saw that this behavior was probably added for https://github.com/envoyproxy/go-control-plane/issues/46. 
Is this working as intended now?
Shouldn't the go-control-plane server respond with whatever resources are requested? Am I missing something in my usage?

FWIW: This is one of the tests in which we use the go-control-plane server: https://github.com/grpc/grpc-go/pull/4350

**Comment by easwars** [comment]
Gentle ping ...

**Comment by kyessenov** [comment]
The goal of the "ads" flag was to correct for the flaw in the protocol. Envoy would incrementally request {R1}, {R1, R2}, ... repeatedly and we would have to create temporary versions if we respond to each intermediate request.

I think you can just set the flag to "false". It doesn't mean aggregated discovery stops working. ADS would just be treated as pure multiplexed xDSes.
