### ISSUE TITLE
REST Long Polling

### ISSUE THREAD

**Issue by austince** [envoyproxy/go-control-plane#432]
The xDS docs for the REST-JSON variant of the protocol mention that long polling is available for xDS singleton APIs (https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#rest-json-polling-subscriptions).

I'm wondering if any of the implementations here (i.e. the [ManagementGateway](https://github.com/envoyproxy/go-control-plane/blob/32fa50d1e2f99dae1647bd1ae0a68cc511e50261/pkg/test/server.go#L81-L118)) support this out of the box or, if not, what changes would be necessary to support it?

**Comment by alecholmez** [comment]
I believe the grpc gateway supports RESTful long polling out of the box: https://github.com/grpc-ecosystem/grpc-gateway#supported

**Comment by austince** [comment]
Thanks for the pointer @alecholmez! I'll take a look at that. Do you know why long polling is explicitly mentioned in the envoy docs, if it is not implemented here?
