### ISSUE TITLE
Cache for custom resources without individual versioning

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [envoyproxy/go-control-plane#433]
Hey, [Kuma](https://kuma.io) maintainer here 👋 

We reuse XDS protocol with custom resources across different parts of the code
* Exchange Kuma policies between control planes in multizone deployment
* Provide information about Envoys to Prometheus
* Implement HDS

We loved that you introduced `Server#StreamHandler` that can take any resource. It [greatly simplified](https://github.com/kumahq/kuma/blob/master/pkg/mads/v1/service/mads.go) our implementation of servers.

The problem is that `Snapshot` does not support custom resources.
Our solution for the time when we introduced this was to have a copy of SimpleCache with [Snapshot as an interface](https://github.com/kumahq/kuma/blob/master/pkg/util/xds/v3/cache.go#L30)

We would like to get rid of this code and contribute to the project. Since the time we implement this, you introduced `LinearCache + Mux`. This _almost_ solves our issue, but not quite. We don't use `resourceNames` in our custom XDS therefore we don't need versioning on the individual resources.
LinearCache has `UpdateResource` and `DeleteResource` which is inconvenient in our case when compared to `SetSnapshot`. Technically, we could do delta on resources our side and call individual methods, but then every call triggers `watchAll` watches. This means If at a given moment we have 10 resources to update, we will trigger 9 updates for no good reason.

I see two options
1) Create `LinearCache#SetResources` that replaces `resources`, triggers individual watches by name (in our case no watches) including deleted resources, and only then trigger `watchAll` watches.
2) Create a separate cache for custom resources that do not version individual resources

I think the first one is better although I want to ask beforehand so I don't break the intention of `LinearCache`. WDYT?

Thanks!

**Comment by alecholmez** [comment]
@jakubdyszkiewicz Hey there!

Some of these problems you face might actually get solved with Incremental xDS going in :)
I'll shortly be opening PRs for Linear and Mux caching which should solve the issue you brought to light regarding excessive watch updates. 

I think the simple cache implementation could certainly use some massaging here. I actually like the idea of a `Snapshot` as an interface.

@snowp what do you think about that? I think doing so would easily enable delta xDS to do custom resources with the simple cache implementation. Especially if we follow the pattern they used above where you can query for the list of supported types, whatever those may be.

I'm assuming you use the SOTW xDS protocol? When you say individual resource versions, you mean how when you set a snapshot you need to provide a version correct? SOTW uses a request/response level version that is the tracker for stream state. I don't think we can remove that as it is defined in the xDS spec. Maybe I'm misunderstanding something here though?

**Comment by jakubdyszkiewicz** [comment]
Yes, we are using SOTW xDS.

For "individual resource versioning" what I meant is that with Linear cache you can have 3 resources:
* res1 - version 1
* res2 - version 2
* res3 - version 3

and the client can send 3 DiscoveryRequests with resourceNames
* DiscoveryRequest resourceNames=res1
* DiscoveryRequest resourceNames=res2
* DiscoveryRequest resourceNames=res3

so when res1 is changed you only send changed res1 from the server, not all of them. It's fantastic for the EDS changes but we don't use it for our xDS.

or you can have a client that sends one DiscoveryRequest with empty resourceNames and send all resources even that only 1 is changed.

The latter works great for our use case for now

> I actually like the idea of a Snapshot as an interface.

The only problem I can see is that it is a pretty big breaking change.

**Comment by alecholmez** [comment]
> or you can have a client that sends one DiscoveryRequest with empty resourceNames and send all resources even that only 1 is changed.

I think this is the current functionality of the SOTW code though isn't it? We send all back regardless of the individual resource version? That's currently how the Simple snapshot cache works, and I believe it's the same for the Linear cache. 

I'm not opposed to adding a simple SetResources in the linear cache, I think that would be helpful but i'd also like to keep the current interface with Update/Delete since after all it is a list. 

That is certainly a big breaking change, and with us developing a release cycle now we'd have to work that in somehow if we do go down that route

**Comment by jakubdyszkiewicz** [comment]
> I think this is the current functionality of the SOTW code though isn't it? We send all back regardless of the individual resource version? That's currently how the Simple snapshot cache works, and I believe it's the same for the Linear cache.

It is, although with UpdateResource, when I want to send 3 resources, the version will change 3 times therefore most likely we will exchange DiscoveryRequest/Response 3 times.

> I'm not opposed to adding a simple SetResources in the linear cache, I think that would be helpful but i'd also like to keep the current interface with Update/Delete since after all it is a list.

Ok, great! Let me try to implement this
