### ISSUE TITLE
Avoid repeated push of rejected configuration

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/go-control-plane#46]
If envoy rejects a config, the snapshot cache will attempt to push the same config immediately after envoy requests it again. If envoy does not limit its requests, the server will drive envoy into a loop of request-receive-reject, potentially causing unnecessary CPU load.

**Comment by kyessenov** [comment]
Tracking issue in envoy: https://github.com/envoyproxy/envoy/issues/2169

**Comment by gsagula** [comment]
@kyessenov It saw that you are tracking this 2169 ^^. I'll be pushing the PR over the weekend. Quick question: Do you know by any chance what would be a good baseline to detect continuous bursts (requests/sec). We are not making it configurable for now. Thanks!

**Comment by kyessenov** [comment]
I don't think I know the number that was validated in the real world. I think something <100qps is a realistic upper-bound for config updates per proxy. It might be worth trying to push invalid configs for each xDS at certain qps, and see CPU impact. Currently, envoy just consumes all available CPU while trying to invalidate the config.

**Comment by gsagula** [comment]
I will try that and if I can get a more accurate number, but something like <100qps seems realistic for me too. Thanks!

**Comment by mihaitodor** [comment]
I think this has been fixed here: https://github.com/envoyproxy/envoy/pull/4787 It exposes `rate_limit_settings` in the `ads_config` of the Envoy config.

**Comment by kyessenov** [comment]
Correct. It would be nice to wire the feedback from the server. Some messages are useful (invalid config, missing reference, etc).

**Comment by mihaitodor** [comment]
Hmmm... I'm using the [Callbacks](https://github.com/envoyproxy/go-control-plane/blob/9877870102f198dded66227f17d52e96839ff441/pkg/server/v2/server.go#L59) to implement the `OnStreamResponse` method and I get this message when adding a duplicate listener: `Error adding/updating listener(s) whoami-http-one:10003: cannot bind '192.168.168.168:10003': Address already in use`. It also provides error code 13.

Not sure if this is what you're referring to, though.

**Comment by kyessenov** [comment]
Yeah, it is just there is no way to plug in server side rate limiter ATM. Some of these errors are ephemeral so not sure what action to take anyways until it settles (e.g. the older listener stops listening in your case)

**Comment by mihaitodor** [comment]
Ah, I see what you mean now. Thanks for the clarification! I'm not sure either how the server should behave, but the default `rate_limit_settings` in Envoy seem excessive to me. Retrying so fast can easily DDoS the go-control-plane server and I'm curious why anyone would need these retries to happen faster than once / second or so...

**Comment by akshaysngupta** [comment]
Another option could be for control plane to allow implementors to choose if they want to retry on a specific error.

In following code, we can introduce a callback for `OnNACK(error_detail)` which can evaluate the error and decide to retry.

![image](https://github.com/envoyproxy/go-control-plane/assets/5294363/6380f29f-f275-4bc1-85b2-ccea3b278150)
