### ISSUE TITLE
SOTW linear cache bug

### ISSUE THREAD

**Issue by s-matyukevich** [envoyproxy/go-control-plane#463]
Steps to reproduce:
1. envoy sends wildcard Discovery request with type `type.googleapis.com/envoy.config.cluster.v3.Cluster` (this always happens on startup)
2. The control plane responds with a cluster list, which contains a single cluster: clusterA
3. envoy sends another request with type `type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment` and `resource_names` parameter set to `["clusterA"]`
4. ClusterLoadAssignment is handled through LinearCache. The cache responds with the latest set of endpoints for clusterA 
5. The control plane decides to add another cluster and sends a new DiscoveryResponse to envoy with resources list containing the definitions for both clusterA and clusterB
6. envoy now needs to receive the list of endpoints for clusterB. It sends a new DiscoveryRequest to the control plane with `resource_names` parameter set to `["clusterA", "clusterB"]` Also an important detail is that `version_info` in this request is set to the latest version received from the control plane on step 4.
7. Another important detail is that clusterA and clusterB versions stored in the linearCache [versionVector](https://github.com/envoyproxy/go-control-plane/blob/main/pkg/cache/v3/linear.go#L50) are identical (This could easily happened if the both were set via [SetResources](https://github.com/envoyproxy/go-control-plane/blob/main/pkg/cache/v3/linear.go#L192) method, which assigns identical versions to all resources it updates in the versionVector)
8. Next, LinearCache iterates over requested resources from the request in order to determine are there any stale resources (this happens [here](https://github.com/envoyproxy/go-control-plane/blob/main/pkg/cache/v3/linear.go#L237)) It doesn't detect any stale resources because the version received in the Discovery request matches the version for both clusterA and clsuterB. 
9. clusterB endpoints aren't sent to envoy until the next endpoint update happens for either clsuterA or clusterB

**Comment by zhishi** [comment]
this is a known bug, such as #399 which I opened long time ago. I'm surprised this bug is still not fixed since it breaks the xDS protocol definition (which I think a very serious problem).
