### ISSUE TITLE
Delta xDS doesn't respond with anything if the snapshot for a node is empty. This causes envoy to fail its healthcheck.

### ISSUE THREAD

**Issue by s-matyukevich** [envoyproxy/go-control-plane#465]
We use a combination of static and dynamic resources for our envoys and sometimes we want envoy to start with an empty dynamic_resources list. This doesn't work with the current delta xDS implementation because [here](https://github.com/envoyproxy/go-control-plane/blob/main/pkg/cache/v3/delta.go#L34) we check whether there were any updates and if no, we just open a new watch and don't send DeltaDiscoveryResponse to the client. As I mentioned in the issue title, this causes envoy to stay in a non-ready state (and if you use `/ready` endpoint for the liveness probe in k8s, which is standard practice, your envoy pod will be terminated)

This could be easily fixed if we first check whether the [previous version](https://github.com/envoyproxy/go-control-plane/blob/main/pkg/cache/v3/delta.go#L61) is empty in the stream state and if yes - respond anyway, even if the resource list is empty. I can send a PR with the fix if you think this is a good idea.

cc @alecholmez

**Comment by snowp** [comment]
I don't think this is something we'd want to enable by default as it's a pretty important feature for any system that relies on observing the incoming requests or pending watches in order to generate the initial configuration: the fact that no response is sent ensures that Envoy will block startup until the snapshot is set, which is preferable over Envoy coming up without resources in certain deployments.

I'd suggest setting an empty snapshot in this case, or if there is a need for more sophisticated default handling we can consider making that configurable

**Comment by s-matyukevich** [comment]
> I'd suggest setting an empty snapshot

That's actually what we did. To clarify the point: I am not suggesting sending a response if no snapshot is set for the node, I want to send an empty response if an empty snapshot is used.

**Comment by snowp** [comment]
Ah yea I misunderstood. I think this makes sense for wildcard mode (you subscribe for all resources but there are none) but not for regular subscription mode (you subscribed for resource X Y Z but none of them exist). I assume the resources blocking your startup is either clusters or listeners?

@htuch thoughts on when a Delta server should respond with an empty response?

**Comment by s-matyukevich** [comment]
> I assume the resources blocking your startup is either clusters or listeners?

Exactly. Right now we create a dummy cluster as a workaround.

**Comment by htuch** [comment]
@snowp I think it wouldn't be incorrect to have a `DeltaDiscoveryResponse` that had empty add/removes being used to trigger initialization if that's what's desired. CC @envoyproxy/api-shepherds for second opinion.
