### ISSUE TITLE
can not find raw_body & dynamic_metadata in RateLimitResponse

### ISSUE THREAD

**Issue by du2016** [envoyproxy/go-control-plane#468]
can not find raw_body & dynamic_metadata in RateLimitResponse, [rls proto](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/ratelimit/v3/rls.proto.html) have raw_body & dynamic_metadata field

**Comment by alecholmez** [comment]
I'm not entirely sure what's being asked here. Those fields are located here: https://github.com/envoyproxy/go-control-plane/blob/main/envoy/service/ratelimit/v3/rls.pb.go#L249-L257
