### ISSUE TITLE
Extract Cookie from HTTP Request in envoy 

### ISSUE THREAD

**Issue by ImMukulTaneja** [envoyproxy/go-control-plane#472]
Hey,

I have added an authorization gateway using envoy proxy and istio-sidecar. I implemented `check` grpc API in  [auth](github.com/envoyproxy/go-control-plane/envoy/service/auth/v3)

For authorization, I need session token in cookie. But there is no field in `check` [request ](https://github.com/envoyproxy/go-control-plane/blob/v0.9.9/envoy/service/auth/v3/external_auth.pb.go#L39) to get the cookie from http request.

Can anyone help me with this ?

P.s : I am putting my first issue in any public repo, sorry if it seems naive :)

**Comment by alecholmez** [comment]
Maybe the session token is located here? https://github.com/envoyproxy/go-control-plane/blob/v0.9.9/envoy/service/auth/v3/external_auth.pb.go#L45
