### ISSUE TITLE
[Help Wanted] Unable to disable healthy_panic_threshold

### ISSUE THREAD

**Issue by elliotfehr** [envoyproxy/go-control-plane#482]
As far as I can tell it does not seem possible to set `healthy_panic_threshold` to `0.0` via xds using the go control plane. When setting `cluster.CommonLbConfig.HealthyPanicThreshold.Value = 0.0` in go code, the envoy instance that is connected will load a config of `healthy_panic_threshold: {}`. I believe this is due to the `float64` in the percent proto having `omitempty` set at: https://github.com/envoyproxy/go-control-plane/blob/main/envoy/type/v3/percent.pb.go#L95. Go will see the `0.0` value as empty and omit it, which prevents it from being sent to the envoy instances connecting to the control plane.

I'm not sure if this should be considered a bug with the control plane or with envoy itself (since the protobufs are pulled from there) or if there is a workaround that I'm not seeing here. Either way would appreciate any help here. Thanks!

**Comment by elliotfehr** [comment]
Still encountering this issue and would appreciate help finding a workaround

**Comment by elliotfehr** [comment]
No stalebot

**Comment by elliotfehr** [comment]
no stalebot

**Comment by jpeach** [comment]
@elliotfehr IIUC, the percent value would only be omitted if the protobuf is marshaled as JSON. AFAIK gRPC doesn't use the json encoding, so I'd expect it to work over xDS. If you needed to marshal into a bootstrap message to write an envoy startup configuration file, [this](https://github.com/golang/protobuf/issues/1371#issuecomment-938741500) might help.
