### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by easwars** [envoyproxy/go-control-plane#492]
Could we please have a new release? Doesn't have to be a stable release as discussed in https://github.com/envoyproxy/go-control-plane/issues/467.

There have been significant updates to the protos which we, grpc-go, rely on and a new release would help us pin our dependency .

**Comment by renana** [comment]
+1 we are consistently seeing this warning that is a result of the control plane being behind the main envoy release:
`external/envoy/source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.config.cluster.v3.Cluster Using deprecated option 'envoy.config.cluster.v3.Cluster.common_http_protocol_options' from file cluster.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.`

**Comment by alecholmez** [comment]
Hi there, `v.0.9.10` can certainly be in order! We're stuck on the upgrade for protobuf in the upstream repo so before `1.0` its probably safe to cut a patch
