### ISSUE TITLE
Support for envoy.filters.network.postgres_proxy

### ISSUE THREAD

**Issue by gschier** [envoyproxy/go-control-plane#497]
I noticed there is already support for most filters (mongo, redis, etc) but postgres is still missing. Is this because the postgres filter is currently still "experimental" according to the docs? If so, is there another way to configure it without having the official proto types?

**Comment by jpeach** [comment]
Is this what you are looking for?

https://github.com/envoyproxy/go-control-plane/tree/main/contrib/envoy/extensions/filters/network/postgres_proxy/v3alpha
