### ISSUE TITLE
protoc-gen-go and protoc-gen-validate versions used for go-control-plane v0.9.1

### ISSUE THREAD

**Issue by mramakrishnaprasad** [envoyproxy/go-control-plane#499]
Hi 

We are using go-control-plane v0.9.1 for configuring the Envoy from the Go control plane. 

I understand the go code in this repository is generated from the Envoy v2 protobufs. I would like to know which version of protoc-gen-go and protoc was used to generate this code. Could you please share the version details?

Appreciate your help!

Rama

**Comment by alecholmez** [comment]
@mramakrishnaprasad Hi there, v0.9.1 is generated from `v2`, the version of those will be found in the envoy repository. Their bazel build is what drives the generations of the proto stubs here.
