### ISSUE TITLE
Help with cache.NewSnapshot breaking change and outdated documentation

### ISSUE THREAD

**Issue by ekristen** [envoyproxy/go-control-plane#513]
I'm currently on 0.9.9 and looking at going to 0.10.0 and it looks like a breaking change was introduced. It also appears that this change was accidentally omitted from the changelog, unless I missed it?

It appears that the cache.NewSnapshot function was changed to take a different set of arguments however all existing documentation still refers to the old function arguments. 

Can anyone help with an upgrade example?

**Comment by nfuden** [comment]
Per the test here: 
https://github.com/envoyproxy/go-control-plane/blob/c8b9204f470206d7791373eb3da11b7a0f5e9a37/pkg/cache/v3/snapshot_test.go#L35

and the list of resource types that it validates here: https://github.com/envoyproxy/go-control-plane/blob/996a28b416c6313efc2411e63329b0c2dc5fe24b/pkg/cache/v3/resource.go#L38

You could go from
`
snapshot := cache.NewSnapshot("1.0", endpoints, clusters, routes, listeners, runtimes)
`
To
`
snapshot := cache.NewSnapshot("1.0",  map[resource.Type][]types.Resource{
		resource.EndpointType: {endpoints},
		resource.ClusterType: {clusters},
		resource. RouteType: {routes},
		resource. ListenerType: {listeners},
		resource. RuntimeType: {runtimes},
	})
`

and one of the nice things about the signature change (other than extensibility) is that if you only care about a subsection of the old arguments you no longer have to specify all the slices in this map.

Take the above comment with many grains of salt as I have not tested/used 0.10.0 and inspected the test suite to derive this.

**Comment by ekristen** [comment]
Thanks @nfuden I'll have to give that a try. I looked at the tests but it was a bit confusing. Mainly trying to understand the map[string] bit first, guess maybe that's making room for expansion in the future any that's why there is only a single entry `resource.Type`? 

I'll give this a shot.

**Comment by alecholmez** [comment]
Hi there! I will update the documentation, it is old and needs to be brought up, we have changed quite a bit since that was written. Sorry for the inconvenience I will try and knock that out tomorrow

**Comment by alecholmez** [comment]
Hi there! Just opened this PR to address some of these issues: https://github.com/envoyproxy/go-control-plane/pull/520
