### ISSUE TITLE
scoped route consistency checking is wrong

### ISSUE THREAD

**Issue by jpeach** [envoyproxy/go-control-plane#517]
I'm not convinced that I completely understand how scoped routes are put together, but I'm fairly sure that the consistency check is not correct. In `getListenerReferences`, we crack the connection manager and, if SRDS is being used, add the name of the scoped routes element to the set of resource references that we expect:

https://github.com/envoyproxy/go-control-plane/blob/d02f089307688a1fe99f1cdf9f66623f07707fa2/pkg/cache/v3/resource.go#L229-L234

However, this isn't how scoped routes work, because there should be a `ScopedRouteConfiguration` resource for every unique key. The name in the HCM `ScopedRoutes` fields is irrelevant and does not need to match any resources. IIUC, what happens is that Envoy collects all the `ScopedRouteConfiguration` resources, and indexes the correct one based on the results of the key builder match. There's no direct link between the HCM and the scoped route resources (seems like a problem with the API design).

So for consistency checking, I think that:
* `ScopedRouteConfiguration` resources should be checked to ensure they name a valid `RouteConfiguration`
* the name in the HCM `ScopedRoutes` field should not be checked
* if HCM enables SRDS, then at least one `ScopedRouteConfiguration` must be present
* additional `ScopedRouteConfiguration` resources are allowed

**Comment by jpeach** [comment]
@mtagstyle @chaoqin-li1123 am I properly understanding the resource relationships here?

**Comment by chaoqin-li1123** [comment]
@stevenzzzz

**Comment by jpeach** [comment]
> The name in the HCM `ScopedRoutes` fields is irrelevant and does not need to match any resources.

Pretty sure that this is right, but I had some doubt so I asked for some clarification in https://github.com/envoyproxy/envoy/issues/19113.

**Comment by stevenzzzz** [comment]
basically the http_connection_manager::v3::ScopedRoutes::name is not a "resource name". the "scope name"/resource name in SRDS is ScopedRouteConfiguration::name.  

the former name is only used in metrics.

**Comment by jpeach** [comment]
Thanks for the confirmation @stevenzzzz! So it sounds to me as though the PR does the right thing, as described above.
