### ISSUE TITLE
What flags are being used to generate the .pb.go files?

### ISSUE THREAD

**Issue by mtagstyle** [envoyproxy/go-control-plane#523]
I have a strange question. I'm building a version of GoControlPlane with a custom version of the XDS protos (under /envoy) (Both Envoy and the management server are using these custom protos). 

I've currently got both the .pb.go files building correctly, but when trying to add protoc-gen-validate as per (https://github.com/envoyproxy/protoc-gen-validate) to generate the *.pb.validate.go files, some of them fail during unit tests due to package import collisions. I suspect the problem lies with either the version of protoc/protoc-gen-validate, or the options I'm passing to them.

```
github.com/envoyproxy/go-control-plane/envoy/extensions/filters/network/ext_authz/v3/ext_authz.pb.validate.go:104:11: assignment mismatch: 2 variables but 1 value

github.com/envoyproxy/go-control-plane/envoy/extensions/filters/network/ext_authz/v3/ext_authz.pb.validate.go:104:14: undefined: v3
```

My question is: **Where can I see the how the .pb.go, and .pb.validate.go files are being generated?** Currently, this is done by the Azure pipeline, and I'm not quite sure where to reference it.

**Comment by mtagstyle** [comment]
@alecholmez

**Comment by jpeach** [comment]
Pretty sure this comes from bazel rules in the main envoy repo?

**Comment by alecholmez** [comment]
Ah yea so it happens here: https://github.com/envoyproxy/envoy/blob/main/tools/api/generate_go_protobuf.py

With a mix of Bazel things as James has said above. It's a bit of a spread out process unfortunately

**Comment by mtagstyle** [comment]
Yep. This helped me figure out what my issue was (Some bad package name options in my custom protos).

Thanks! Will mark as closed.
