### ISSUE TITLE
Switch to new Go protobuf v2 module

### ISSUE THREAD

**Issue by jpeach** [envoyproxy/go-control-plane#524]
Upstream switched to a new Go protobuf module, [protobuf v2](https://go.dev/blog/protobuf-apiv2). go-control-plane should fully switch over to this so that client projects can switch too. I think the main change that will be needed is to switch the protoc toolchain over to generate wrapper code with the new module.

**Comment by alecholmez** [comment]
+1 for this. We looked into this previously and I believe the action items were:
- Update rules_go
- Update Envoy's internal bazel pipeline
- Update the build script: https://github.com/envoyproxy/envoy/blob/main/tools/api/generate_go_protobuf.py

**Comment by jpeach** [comment]
>     * Update rules_go: [proto: add go_proto_apiv2 and go_grpc_apiv2 compilers bazelbuild/rules_go#2522](https://github.com/bazelbuild/rules_go/issues/2522)

Oof, that does not look promising ...

**Comment by alecholmez** [comment]
> Oof, that does not look promising ...

Yea... this is a big rabbit hole I went down a while back, might be worth revisiting though

**Comment by alecholmez** [comment]
I have a PR open for this now: https://github.com/envoyproxy/envoy/pull/21790

**Comment by alecholmez** [comment]
Okay looks like this pr: https://github.com/envoyproxy/envoy/pull/21790 got merged so we can now proceed here.

**Comment by jpeach** [comment]
> Okay looks like this pr: [envoyproxy/envoy#21790](https://github.com/envoyproxy/envoy/pull/21790) got merged so we can now proceed here. @jpeach would you be interested in picking this back up?

I can probably take a look in a week or so.

**Comment by yckbilly1929** [comment]
https://github.com/envoyproxy/go-control-plane/pull/607

Would like to know if we will resolve this issue together with this PR?
