### ISSUE TITLE
VHDS Support

### ISSUE THREAD

**Issue by mtagstyle** [envoyproxy/go-control-plane#525]
(Feel free to mark this as a dupe if necessary)

I'm planning on adding VHDS support, but having trouble understanding the history of this feature request...

VHDS was initially requested in https://github.com/envoyproxy/go-control-plane/issues/310. This issue was linked against https://github.com/envoyproxy/go-control-plane/issues/323, which "fixes" 310. Could someone comment on what they mean by "fixes" the issue?

Next some questions regarding implementation:

**Server**
- VHDS can only be used with the delta protocol, does that include both the aggregated and non-aggregated variants?

**SimpleCache**
- VHDS resource names, undergo a naming convention based on the route that it belongs to, and the name of the host header as per [this doc](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/vhds.html?highlight=vhds#virtual-host-resource-naming-convention). Therefore, I imagine the consistency check done as part of the snapshot, will not include virtual hosts? (Because the routing configuration never explicitly mentions virtual hosts to be used)

I.e. Can someone confirm that: There will never be any resources that need to explicitly reference a virtual host when using VHDS.

- Does [this](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/vhds.html#compatibility-with-scoped-rds) just mean that VirtualHost resource names, can either be in the form of "\<route resource name>/\<host entry>" or "\<scoped route resource name>/\<host entry>"?

**Comment by mtagstyle** [comment]
@jpeach @alecholmez

**Comment by jpeach** [comment]
Hey @mtagstyle , I haven't tried to use VHDS, so I don't really know the details. As far as consistency checks go, I'd suggest starting loosely and tightening up the check as you learn more about how Envoy treats VHDS.

In general, the direction we are moving towards in the cache is to reduce the coupling to specific envoy types. So if we can support VHDS in all the cache types without introducing hard bindings to the VHDS type, that would be better IMHO.

**Comment by mtagstyle** [comment]
Ok some follow up after playing around:
```
VHDS can only be used with the delta protocol, does that include both the aggregated and non-aggregated variants?
```
- Envoy currently only supports the Delta API (Non-Aggregated). When attempting to configure VHDS as delta ADS, it will complain on [this line](https://github.com/envoyproxy/envoy/blob/main/source/common/router/vhds.cc#L42).
- Some brief research into **why delta ADS isn't supported** as follows
- Prior attempts to introduce VHDS using Delta ADS: 
> https://github.com/envoyproxy/envoy/pull/13463
> https://github.com/envoyproxy/envoy/pull/12701
- The above PRs seem to be blocked by no fix to the following issues:
> https://github.com/envoyproxy/envoy/issues/12742
> https://github.com/envoyproxy/envoy/issues/12158

```
I.e. Can someone confirm that: There will never be any resources that need to explicitly reference a virtual host when using VHDS.
```
I don't think the consistency checking for the existence of virtual hosts, as the VHDS source for routes never explicitly calls out any routes.

**Comment by mtagstyle** [comment]
@dmitri-d Could you confirm if my comment above is true?
