### ISSUE TITLE
Update go build version to something current

### ISSUE THREAD

**Issue by jpeach** [envoyproxy/go-control-plane#532]
In #272, `go.mod` was downgraded to Go 1.11. While that was an unsupported release at the time, it's still unsupported. Per the Go [release policy](https://go.dev/doc/devel/release), the last 2 major releases are supported, which at time of writing puts us on 1.17 or 1.16.

The downgrade was done to support [grpcurl](https://github.com/fullstorydev/grpcurl), which I guess ended up taking a go-control-plane dependency via gRPC. grpcurl is on Go 1.15 now, so that seems like a safe minimum. My preference would still be to use oldest supported Go release.

**Comment by jpeach** [comment]
ping @alecholmez @snowp @kyessenov

**Comment by jpeach** [comment]
grprc-go depends on go-control-plane and Go 1.14, so it would be less disruptive to only bump up to 1.14.

**Comment by alecholmez** [comment]
This works for me let's bump it up

**Comment by jpeach** [comment]
Ping @markdroth for gRPC perspective.

IIUC, bumping the go-control-plane version pasts Go 1.14 (which is where gRPC is) would have no immediate ill effects. The risk would be that if go-control-plane starts to use > 1.14 language features, that would not build in a Go 1.14 program (and people using gRPC might get a nasty surprise).

**Comment by markdroth** [comment]
@dfawley is the right person to weigh in on grpc-go issues.

**Comment by sunjayBhatia** [comment]
grpc-go also mentions it should be used with `any one of the three latest major releases.` ([link](https://github.com/grpc/grpc-go#prerequisites))

probably worth bumping up the module requirement there to ensure that statement is correct as well

**Comment by sunjayBhatia** [comment]
sent https://github.com/grpc/grpc-go/pull/5102 as well to start a discussion
