### ISSUE TITLE
[question]when will v0.10.2 release?

### ISSUE THREAD

**Issue by zirain** [envoyproxy/go-control-plane#534]
when will v0.10.2 release, Is there any plan?

**Comment by alecholmez** [comment]
Hi there @zirain, we'd like to land a few more features first before we cut 0.10.2 but hopefully we can get that done in January

**Comment by zirain** [comment]
> Hi there @zirain, we'd like to land a few more features first before we cut 0.10.2 but hopefully we can get that done in January

thx!!!
