### ISSUE TITLE
Question to init state of ring hash based LB

### ISSUE THREAD

**Issue by minopolous** [envoyproxy/go-control-plane#539]
The documentation says nothing, if for two ports in a deployment the same hash ring is set up (if the hosts are for both ports at the same place in the ring and, if using the same input to the hash function we'd expect the same targeted host), or if the positioning in the ring is random.
What can be seen is, that different ports defined in istio are targeting different hosts (stickyness is isolated between ports).
Asking in the direction of - if there is any chance to share stickyness between ports by tuning configuration...

**Comment by sunjayBhatia** [comment]
This question might be better suited for the main `envoy` repository

**Comment by minopolous** [comment]
Agreed. Opened https://github.com/envoyproxy/envoy/issues/19739 for this.
