### ISSUE TITLE
Is Consistent() correct?

### ISSUE THREAD

**Issue by rerorero** [envoyproxy/go-control-plane#54]
Hi. Thank you very much for the implementation. This helps me a lot.

I tried this but faced an error at cache.Consitent(). It compares with the numbers of endpoints, but GetResourceReference(cluster items) returns the number of ClusterConfig, not the number of endpoints. It returns at most one for each cluster item. 
https://github.com/envoyproxy/go-control-plane/blob/master/pkg/cache/snapshot.go#L74-L75
https://github.com/envoyproxy/go-control-plane/blob/master/pkg/cache/resource.go#L87-L95

**Comment by rerorero** [comment]
Oh, sorry, I missunderstood. I found that Consitent() compares the nembers of ClusterLoadAssignements which has some endpoints.

**Comment by kyessenov** [comment]
I'm glad you found this useful. Let me know if you spot anything else.
