### ISSUE TITLE
Multiple Envoy Instances with same node ID?

### ISSUE THREAD

**Issue by gschier** [envoyproxy/go-control-plane#545]
I found the definition of `node.id` and `node.cluster` to be quite minimal in the Envoy documentation, as well as in this repo. 

I have a use case where I need to run multiple Envoy instances with identical configuration, and was wondering if it's possible to simply use the same node ID and cluster for each instance, as it seems to work in my testing. Essentially, I want to avoid the complexity of having the control plane manage a pool of node IDs.

**Comment by sunjayBhatia** [comment]
This is what [Contour](https://projectcontour.io/) currently does since we are still using basic SOTW xDS and expect every Envoy instance to be identical

**Comment by alecholmez** [comment]
@gschier yes. Node ID and cluster serve that purpose :) 

Cluster is more important as it is used in load balancing, grouping, etc....

**Comment by gschier** [comment]
Thanks for the clarification @alecholmez! 👍🏻
