### ISSUE TITLE
Is there any rule about about wellknown package?

### ISSUE THREAD

**Issue by zirain** [envoyproxy/go-control-plane#552]
Hi folks
Is there any rule that should be followed when someone want add new filter names in wellknown package?

**Comment by alecholmez** [comment]
Please just follow the existing naming schemes in the file. If you wish to open a PR please do I will review

**Comment by zirain** [comment]
thanks for your response.

**Comment by jpeach** [comment]
@zirain You should not need well-known names any more. I think there are a couple of historical cases where the filter name matters, but in general you can use whatever name you want (something that's meaningful to your control plane) and Envoy selects the filter based on the type of the config protobuf.

**Comment by shashankram** [comment]
> @zirain You should not need well-known names any more. I think there are a couple of historical cases where the filter name matters, but in general you can use whatever name you want (something that's meaningful to your control plane) and Envoy selects the filter based on the type of the config protobuf.

@jpeach since when was this change introduced in Envoy? Previously, we could simply specify the filter name without the typed config spec in the Go types, so curious.

**Comment by sunjayBhatia** [comment]
I believe Envoy 1.22: https://www.envoyproxy.io/docs/envoy/v1.22.2/version_history/v1.22.0#deprecated

**Comment by shashankram** [comment]
> I believe Envoy 1.22: https://www.envoyproxy.io/docs/envoy/v1.22.2/version_history/v1.22.0#deprecated

Thanks @sunjayBhatia. Is there a place where we can see the list of filters and their corresponding types?
For e.g., the http router filter uses the type `type.googleapis.com/envoy.extensions.filters.http.router.v3.Router`. I'd like to see the types for other filters as well, such as HTTP RBAC.

Is it also safe to discontinue the use of the wellknown names for filters prior to v1.22?

**Comment by sunjayBhatia** [comment]
for xDS v3 and above I think all the type urls match well to package names so you can follow those to find the types

e.g. this page has all the http filters and I usually use the type url/package to correlate to get the go package from this repo: https://www.envoyproxy.io/docs/envoy/v1.22.2/api-v3/config/filter/http/http

**Comment by sunjayBhatia** [comment]
release notes imply the filter name usage was "long deprecated" but I haven't found what release that was started in, I think it has generally been the case you can/should use the types for quite a while if not forever

**Comment by shashankram** [comment]
Do the non-http filters (e.g. tcp_proxy) still rely on the wellknown names?

**Comment by jpeach** [comment]
> @jpeach since when was this change introduced in Envoy? 

I guess some time prior to 2020, maybe 1.12-ish?

xref https://github.com/envoyproxy/go-control-plane/issues/293

**Comment by shashankram** [comment]
> you should use the type in the config for non HTTP filters as well, rather than solely the name

But does it matter what name you use for non-HTTP filters? For e.g., do we need to use `wellknown.TCPProxy` for the `tcp_proxy` filter or can it be any name?

I came across https://github.com/envoyproxy/envoy/commit/8cb6862fe6099cd8583a64ff037ecdeaf0e939fa which seems to only affect extension filters, so wasn't sure.

**Comment by shashankram** [comment]
> > you should use the type in the config for non HTTP filters as well, rather than solely the name
> 
> But does it matter what name you use for non-HTTP filters? For e.g., do we need to use `wellknown.TCPProxy` for the `tcp_proxy` filter or can it be any name?
> 
> I came across [envoyproxy/envoy@8cb6862](https://github.com/envoyproxy/envoy/commit/8cb6862fe6099cd8583a64ff037ecdeaf0e939fa) which seems to only affect extension filters, so wasn't sure.

For e.g., the [Envoy doc](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/original_dst_filter) suggests to use the filter name for the OriginalDestination ListenerFilter:
`This filter should be configured with the name envoy.filters.listener.original_dst.`

But does the name actually matter?

@jpeach, @sunjayBhatia

**Comment by sunjayBhatia** [comment]
no, the name doesn't really matter, it is used just for annotation, just verified by changing the httpconnectionmanager filter with a non-type url name and everything is fine

**Comment by shashankram** [comment]
> no, the name doesn't really matter, it is used just for annotation, just verified by changing the httpconnectionmanager filter with a non-type url name and everything is fine

Thanks for clarifying. I guess it makes sense to document these clearly in the Envoy docs. I'll open an issue there.

**Comment by shashankram** [comment]
@sunjayBhatia it seems like the name still matters for some filters, see https://github.com/envoyproxy/envoy/issues/21759#issuecomment-1159243250

**Comment by sunjayBhatia** [comment]
ah, well that is a shame it hasn't been fixed everywhere, good find @shashankram
