### ISSUE TITLE
How can I start a health check to our envoys?

### ISSUE THREAD

**Issue by vietanhduong** [envoyproxy/go-control-plane#554]
I'm trying to implement HDS to the control plane, but seem it's not supported yet. So, my question is: how can I start a health check to our envoys (from different clusters)?

**Comment by alecholmez** [comment]
You will need to add your own hds implementation at this moment. That is something that is worth implementing here we just haven't prioritized it yet.

**Comment by vietanhduong** [comment]
@alecholmez Thanks for your response. Currently, I'm faced with a problem that, when I applied a snapshot. I don't know that snapshot has been accepted by the envoy or not. Currently, envoy behavior is retry to pull new snapshot from our `xds_server` if the snapshot is invalid. My question is: Will `hDS` solve my problem?

**Comment by vietanhduong** [comment]
Actually, Envoy when sending a connection request to xDS server will include status information in `ErrorDetails`. I can rely on this information to determine if a Snapshot has been successfully applied.
