### ISSUE TITLE
How to create snapshot that only contains RouteConfiguration

### ISSUE THREAD

**Issue by mostafafarzaneh** [envoyproxy/go-control-plane#556]
Hi,

Just want to know how to create snapshots only with RouteConfiguration? I just changed the `GenerateSnapshot()` in `internal/example/resource.go` to this :

```
func GenerateSnapshot() *cache.Snapshot {
    snap, _ := cache.NewSnapshot("1",
        map[resource.Type][]types.Resource{
            //resource.ClusterType:  {makeCluster(ClusterName)},
            resource.RouteType:    {makeRoute(RouteName, ClusterName)},
            //resource.ListenerType: {makeHTTPListener(ListenerName, RouteName)},
        },
    )
    return snap
}
```

and got this error:

```
mismatched "type.googleapis.com/envoy.config.route.v3.RouteConfiguration" reference and resource lengths: len(map[]) != 1
```

If put the `Listener` in the snapshot too, it runs fine.

**Comment by mostafafarzaneh** [comment]
There is some similar issue #444

**Comment by mostafafarzaneh** [comment]
In https://pkg.go.dev/github.com/envoyproxy/go-control-plane@v0.10.1/pkg/cache/v3#SnapshotCache it states that:
`The snapshot can be partial, e.g. only include RDS or EDS resources.`. Do I miss something?

**Comment by sunjayBhatia** [comment]
yeah that comment is at odds with how the `Consistent` method works, it does in fact check the cluster name referenced in `RouteConfigurations` and `ClusterLoadAssignments` is present in the snapshot

here's a test that shows as well: https://github.com/envoyproxy/go-control-plane/blob/27659a1a988e14059d1dbdb1e92378c4eaee44eb/pkg/cache/v3/snapshot_test.go#L38-L44

**Comment by sunjayBhatia** [comment]
if you are only using a snapshot with routes, do you need to use the `Consistent` method at all?

**Comment by mostafafarzaneh** [comment]
Thank you @sunjayBhatia. My goal was to migrate gradually from static to dynamic. But I ended up adding the LDS as well and now it is working.

Just like to know should one use `Mux` cache for a single resource like RDS? Is it the purpose of the `Mux` cache?

**Comment by mostafafarzaneh** [comment]
> if you are only using a snapshot with routes, do you need to use the Consistent method at all?

Is it considered a good practice?

**Comment by alecholmez** [comment]
Mux cache is designed for splitting resources across various cache implementations: simple + linear. For example, you can serve all resource objects over simple, but endpoints with linear for speed.

Checking to see if your snapshot is consistent is only necessary when you actually are building the config tree. If you only have a single resource type it is not necessary.
