### ISSUE TITLE
How to save Envoy Resources to file

### ISSUE THREAD

**Issue by mostafafarzaneh** [envoyproxy/go-control-plane#560]
I am developing a control plane for our API Gateway. I need to read some basic envoy configuration(envoy YAML files) from the file and populate the Snapshot cache to initialize the control plane.
Furthermore, I have a server that receives RouteConfiguration from services and updates the Snapshot cache based on that.

My questions:
1- How can I convert YAML files to Snapshot cache?
2- What is the best practice to save and retrieve the cache/resources?

**Comment by jpeach** [comment]
> 1- How can I convert YAML files to Snapshot cache?

Read protobuf objects from YAML files, convert to protobuf using https://pkg.go.dev/github.com/golang/protobuf/jsonpb.

> 2- What is the best practice to save and retrieve the cache/resources?

Everyone has different needs. You should just do what works for you.

**Comment by mostafafarzaneh** [comment]
Thanks @jpeach 

> Read protobuf objects from YAML files

Is there any tool for converting YAML files to protobuf objects?
