### ISSUE TITLE
StatefulSession API release

### ISSUE THREAD

**Issue by iglin** [envoyproxy/go-control-plane#567]
Hi! 
I need **envoy/extensions/filters/http/stateful_session/v3** API to be released so I can use it in my company - our policies prohibit to take dev versions of third-party software. 

I have seen that v0.10.2 was planned in January: https://github.com/envoyproxy/go-control-plane/issues/534#issuecomment-1001103247

Now when it is already June, could you please release the library with stateful session API?

**Comment by alecholmez** [comment]
We just release `v0.10.3`
