### ISSUE TITLE
Proposal: Add Node to OnStreamClosed and OnDeltaStreamClosed of Callbacks

### ISSUE THREAD

**Issue by tony612** [envoyproxy/go-control-plane#569]
When we implement a control plane, we may need to watch resources like k8s Ingress/Gateway using k8s informer. To save cpu and memory, we only want to watch specific the resources we care about. Then we can start watching when we get a request and stop watching when the stream closes. With current [Callbacks](https://github.com/envoyproxy/go-control-plane/blob/main/pkg/server/v3/server.go#L62) interface, we can start watching in (the first) `OnStreamRequest`(take sotw for an example) using `Node` in `DiscoveryRequest`, but we can't stop watching in `OnStreamClosed` because the params of doesn't have the `Node`.

So I propose adding Node to `OnStreamClosed` and `OnDeltaStreamClosed`, like:
```
# sotw
type Callbacks interface {
	OnStreamClosed(int64, *corev3.Node)
}

# delta
type Callbacks interface {
	OnDeltaStreamClosed(int64, *corev3.Node)
}
```

Any idea about the proposal? Or maybe there are other solutions to achieve this?

If this is a good idea, I can send a PR for this. But this will be a breaking change :(

**Comment by atollena** [comment]
This is particularly handy when using SnapshotCache. The way we do that is typically to keep two mapping inside every implementations of the `Callbacks` interface:

1. a mapping of `stream -> node id` (a `map[streamKey]stream`, where `streamKey` is a stream ID + a boolean indicating whether it is a delta stream) which is created on the first request on a stream (in `OnStreamRequest`). You can access it in OnStreamClosed to do cleanup and also access the node associated to this stream.
2. a mapping of `node id -> count` (map[string]int) which counts the number of active streams for this node id. You can also add more information inside the mapping, such as the node metadata for this node ID.

I think a lot of implementation of `Callbacks` eventually need this kind of bookkeeping, and it would make sense for `go-control-plane` to offer a pattern for this. I'd suggest something in the form of an interface like:

```
type NodeCallbacks struct {
    OnNodeAdded: func (node *node) // typically calls SetSnapshot for this node
    OnNodeRemoved: func (node *node) // (or OnNodeRemoved: func(nodeId string)) // typically clears snapshots
}
```

Then offer a something to implement the xDS callbacks via this interface:

```
type NodeTrackingCallback struct {
        map[streamKey]stream
        map[string]int
}

type NewNodeTrackingCallback(callbacks NodeCallbacks) NodeTrackingCallback {
        ...
}

// + implementation of xds.Callacks that calls OnNodeAdded/OnNodeRemoved appropriately.
```

This would significantly decrease the complexity of basic control plane functionalities that just call SetSnapshot when a node connects, based on its ID and metdata.

**Comment by alecholmez** [comment]
I think this is a reasonable addition to the callbacks interface. If you'd like to open a PR that makes this change i'd be happy to review.

**Comment by tony612** [comment]
@atollena I'm using a similar solution to track connected nodes like yours(map & callbacks).

`OnNodeAdded` & `OnNodeRemoved` will be a more direct way. But they are very different from the current callbacks, which are all about the lifetime of the streams. If we request more features in the future, we need to add more and more callbacks. Maybe we should discuss more. @alecholmez Any idea for the new NodeTrackingCallback by atollena?

@alecholmez I can open a PR for this soon.

**Comment by tony612** [comment]
@alecholmez I agree that we need to manage nodes in a better way without overloading the callbacks. I don't have a mature idea now but will post it if I have something to discuss.
