### ISSUE TITLE
Implement SDS

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/go-control-plane#57]
- [x] add stubs for SecretDiscoveryService
- [x] add secrets to snapshots
- [ ] work-out ADS semantics for secret fetching
- [x] test and validation

**Comment by kyessenov** [comment]
One item left to do is to resolve ADS semantics with respect to SDS. It seems like it is similar to RDS. We might need to extend `Consistent` function to cover SDS resources.

**Comment by kyessenov** [comment]
Another TODO: fix the unit tests in the `pkg/cache/` to exercise secrets. Need a fake secret for mocking purposes.

**Comment by amukherj1** [comment]
@kyessenov Ideally this should also have UDS support - it has lower configuration overhead.

**Comment by stevesloka** [comment]
hey @kyessenov do you have an idea of what else work needs to be completed to get SDS working? I'm happy to jump in and help out with this.

**Comment by tessykt** [comment]
hello! any news on when this change is going to be merged?
Thank you in advance!

**Comment by gophobic** [comment]
Hey @kyessenov  Is this going to get released with v0.9.7? if it is so when is this going to be released? thanks!

**Comment by kyessenov** [comment]
Yeah, it'll be released. For now, you can just latest SHA.

**Comment by amukherj1** [comment]
@kyessenov does the change #314 mean that I don't have to bother running a separate endpoint for SDS, and can just update the secrets in the same way as rest of the config objects such as listeners, clusters, routes, etc.?
