### ISSUE TITLE
How to build .pb.go files?

### ISSUE THREAD

**Issue by VivekSubr** [envoyproxy/go-control-plane#574]
Hello! So, I need to rebuild go control plane with changes in a few protobufs, like route_components.proto... but I can see that this repo only has the built files and no .protos? It must be referring to envoy repo? 

Can someone please list the steps to rebuild the *.pb.go files?

**Comment by sunjayBhatia** [comment]
Envoy protobufs are synced with this repo in a job in Envoy CI, using this script: https://github.com/envoyproxy/envoy/blob/70d04b6ae7afc409752dd4875ddf6b6860882530/tools/api/generate_go_protobuf.py

**Comment by VivekSubr** [comment]
Thank you, but that script seems to first checkout and then build... losing local changes. :( Ultimately went with plain protoc commands, like 

 sudo protoc --go_out=./gocode --go_opt=paths=source_relative ./envoy/config/route/v3/route_components.proto --proto_path=. --proto_path=/home/vivek/new_envoy/xds --proto_path=/home/vivek/go/pkg/mod/github.com/envoyproxy/protoc-gen-validate@v0.6.7
