### ISSUE TITLE
Support for SkipFilter

### ISSUE THREAD

**Issue by seblaz** [envoyproxy/go-control-plane#575]
Hi,
Is there support for "type.googleapis.com/envoy.extensions.filters.common.matcher.action.v3.SkipFilter"?

**Comment by jpeach** [comment]
Assuming the protobufs are new enough, then it is supported. Deep in the matcher config there will eventually be a config.core.v3.TypedExtensionConfig, where you provide the skip filter as the `typed_config` field.

**Comment by seblaz** [comment]
Hi @jpeach, thank you for your fast response! Do you know how could I include it in an action? Because I tried the following code but I'm getting an error `proto: google.protobuf.Any: unable to resolve "type.googleapis.com/envoy.extensions.filters.common.matcher.action.v3.SkipFilter": not found)` when creating the snapshot:


```go
import (
	"github.com/golang/protobuf/ptypes/any"
	"google.golang.org/protobuf/types/known/anypb"
	core "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
)

any, err := anypb.New(&any.Any{
	TypeUrl: "type.googleapis.com/envoy.extensions.filters.common.matcher.action.v3.SkipFilter",
})
if err != nil {
	panic("error")
}
config := &core.TypedExtensionConfig{
	Name: "skip",
	TypedConfig: any,
}
```

**Comment by jpeach** [comment]
You need to import the right path to get the filter protobuf registered with the grpc runtime, which ought to be "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/common/matcher/action/v3"

**Comment by seblaz** [comment]
I don't how I missed that, thank you so much!
