### ISSUE TITLE
Include Rate-Limit xDS config server related control plane functionality

### ISSUE THREAD

**Issue by renuka-fernando** [envoyproxy/go-control-plane#595]
I am working on https://github.com/envoyproxy/ratelimit/issues/201 which is a feature for updating Rate Limit Service configurations dynamically through an xDS server.

As per https://github.com/envoyproxy/ratelimit/issues/201 I thought of adding the server-related implementation within the go-control-plane repository. Then we could re-use most of the readily available functions here. Hence, I created this git issue to discuss how we can achieve this.

Please share your thoughts on this.

RateLimit config proto: https://github.com/envoyproxy/ratelimit/pull/371

**Comment by alecholmez** [comment]
Hi @renuka-fernando this would be awesome!

I'd actually like to have the rate limit service become a first class citizen of this repo since it's needed for control-plane functionality :)

**Comment by renuka-fernando** [comment]
hi @alecholmez,

Is it possible to add the "no stalebot" label?

**Comment by kkcmadhu** [comment]
hi @renuka-fernando can you kindly add this to java-control-plane too, Please.. It will be super helpful.

**Comment by renuka-fernando** [comment]
> hi @renuka-fernando can you kindly add this to java-control-plane too, Please.. It will be super helpful.

sure, I will. Once @alecholmez confirms the changes on go control plane, I will have a look at the java control plane as well.

**Comment by kkcmadhu** [comment]
kindly, have this included in java control plane too, i am eagerly awating to try it out.

**Comment by renuka-fernando** [comment]
Hi @alecholmez,

Missed one more thing, we have to have a way to generate pb files. As we discussed here https://github.com/envoyproxy/go-control-plane/pull/598#discussion_r1008130688

So I will reopen this again to track it. Source proto files: https://github.com/envoyproxy/ratelimit/pull/371

**Comment by alecholmez** [comment]
@renuka-fernando okay great! Thanks for following up with that.

**Comment by renuka-fernando** [comment]
@alecholmez Can you re-open this? looks like I can't re-open this.
