### ISSUE TITLE
How to set LocalRateLimit#share_key field

### ISSUE THREAD

**Issue by iglin** [envoyproxy/go-control-plane#596]
There is a field "share_key" in Local Rate Limit API, which is not supported by go-control-plane library:
https://www.envoyproxy.io/docs/envoy/v1.22.2/api-v3/extensions/filters/network/local_ratelimit/v3/local_rate_limit.proto#envoy-v3-api-field-extensions-filters-network-local-ratelimit-v3-localratelimit-share-key

We are using go-control-plane library in our control-plane and we need to set this field. The ability to do so is required ASAP, so I am afraid we cannot wait for the next library release (which happens pretty rare). We also cannot fork and change the library ourselves for several reasons. 

Please, tell me, if there is a way to set the field that is not supported by go-control-plane explicitly? Maybe via reflection or some other hacks? 

Also, how fast is it possible to make a library release with support of the LocalRateLimit#share_key field?

**Comment by sunjayBhatia** [comment]
the field in question is available here: https://github.com/envoyproxy/go-control-plane/blob/5e86f7861dc96258c761bce8e7d6103dfa828285/envoy/extensions/filters/network/local_ratelimit/v3/local_rate_limit.pb.go#L56
