### ISSUE TITLE
[Question] Generating go files from dataplane-api proto files 

### ISSUE THREAD

**Issue by vermajit** [envoyproxy/go-control-plane#610]
How is the 'envoy' folder that contains the '.go' version of all '.proto' files generated? Where is the script that is doing the '.proto' to '.go' conversion?

We are using a forked version of envoy and have made certain enhancements to the protobuf messages. We also maintain a forked version of go-control-plane and need the envoy protobuf enhancements on the go-control-plane side. 

Help would be highly appreciated

**Comment by sunjayBhatia** [comment]
the main Envoy repo has a CI job that syncs the protos from that repo with this one: https://github.com/envoyproxy/envoy/blob/7010984aeffe27aea0e6cbf452ef7c20139c6a43/.azure-pipelines/pipelines.yml#L252-L274

**Comment by vermajit** [comment]
@sunjayBhatia  Thanks. This was very helpful
