### ISSUE TITLE
Latest go-control-plane release v0.10.3 is behind Envoy releases

### ISSUE THREAD

**Issue by christos27** [envoyproxy/go-control-plane#619]
Hello,
it appears that the latest release v0.10.3 published in [June 28th](https://github.com/envoyproxy/go-control-plane/releases/tag/v0.10.3) is a few releases short from Envoy.
For example, Envoy has released version:
[v1.24: 1.24.0 (October 19, 2022)](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.24/v1.24)

This leads to the problem of getting "Deprecated field" warning logs, if we want to stick to an official release rather than using commit based versioning.

Can we get a new release that supports Envoy v1.24?
Furthermore, is there a mapping of what Envoy release each go-control-plane release supports?

Thanks!

**Comment by usovamaria** [comment]
@sunjayBhatia Hi! Could you please help us with this issue?

We experience this issue too. We tried to update envoy to 1.24/1.23 versions but found lots of deprecations than cause high disk consumption. 

1. https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.20/v1.20.0#deprecated - a lot of options are deprecated for header matcher and `string_match` [is missing](https://github.com/envoyproxy/go-control-plane/blob/main/envoy/api/v2/route/route_components.pb.go#L2771) but its usage in envoy is recommended.
2. https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.23/v1.23.0#deprecated - engine type/google_re2 is also deprecated but it is still [obligatory](https://github.com/envoyproxy/go-control-plane/blob/main/envoy/type/matcher/regex.pb.go#L34) in control plane.

Hope that support of newer versions of envoy is coming soon :)

**Comment by sunjayBhatia** [comment]
I think there might have been some more things @alecholmez wanted to get in before a new release?

In Contour we don't use tagged versions but stay up to date with Envoy by choosing the latest go-control-plane commit that mirrors the Envoy API for the Envoy release we want to support

**Comment by sunjayBhatia** [comment]
there was discussion here on having a more automated tagging workflow in this issue that fell off the radar (personally due to other commitments): https://github.com/envoyproxy/go-control-plane/issues/391

**Comment by alecholmez** [comment]
Just cut this:
https://github.com/envoyproxy/go-control-plane/releases/tag/v0.11.0

**Comment by alecholmez** [comment]
> there was discussion here on having a more automated tagging workflow in this issue that fell off the radar (personally due to other commitments): #391

With regards to this, I do actually intend on doing that shortly. Wanted to get this last one out and then we can use that as the baseline for the multi-module release. That should solve a lot of these issues
