### ISSUE TITLE
Group nodes to reduce snapshot cache size

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/go-control-plane#62]
Currently, we need two separate identities for proxies:
- an actual ID used to track the state of the proxy on the server - detecting when the proxy goes away, monitoring accepted versions
- a lookup ID used to select the snapshot to push to the proxy.

In the current implementation, hey are treated as 1-1, which means there as many snapshots as there are proxies. In some cases, this is necessary, if all proxies are indeed different. But in many cases, proxies should receive the same configuration if grouped appropriately.

**Comment by Y0Username** [comment]
@kyessenov Has this been addressed yet?

**Comment by kyessenov** [comment]
Sorry, was drawn into other work. You are welcome to contribute changes.

**Comment by Y0Username** [comment]
@kyessenov Any pointers on how to go about this?

**Comment by nakabonne** [comment]
@kyessenov 
In istio, settings are [divided](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/listener.go#L97) for each [NodeType](https://github.com/istio/istio/blob/master/pilot/pkg/model/context.go#L81:6)
How about grouping by node type?

**Comment by kyessenov** [comment]
NoteType seems like a reasonable way to subdivide the total proxy config. I would assume you still need groups per node type since istio has many "gateways" for ingress proxies, as well as each application sidecar having its own config. 

In istio case, a better way to conserve memory would be to share the inner structures within the xDS configuration. For example, all outbound service configuration is generally the same between all proxies; yet, are not reused in terms of golang structures. An obstacle to this is the problem with `google.protobuf.Struct` and `google.protobuf.Any` being represented as frozen JSON/bytes in protobuf library, requiring a deep copy for any small change. I raised an [issue](https://github.com/golang/protobuf/issues/686) about this to the upstream protobuf team.
