### ISSUE TITLE
XDS IPMatcher type not supported

### ISSUE THREAD

**Issue by shishir4saurabh** [envoyproxy/go-control-plane#623]
I wanted to implement a dynamic configuration using Go control plane to the effect of:
                    custom_match:
                      name: ip-matcher
                      typed_config:
                        "@type": type.googleapis.com/xds.type.matcher.v3.IPMatcher
                        range_matchers:
                        - ranges:
                          - address_prefix: 11.12.12.10
                            prefix_len: 32

But I couldn't find support of IPMatcher and subsequent range_matchers in any Go protobuf. 

What is the alternative method to achieve this configuration to be served to Envoy?

Thanks
Shishir

**Comment by alecholmez** [comment]
@shishir4saurabh I'd recommend asking in the envoy repo as well. This generated Go is just a mirror of the data-plane api proto files.
