### ISSUE TITLE
Skipping ResponseTrailerMode is not letting the stream close

### ISSUE THREAD

**Issue by shibin-aot** [envoyproxy/go-control-plane#624]
I just tested the externalprocessor filter with envoy 1.24 and got the below issue.
With below configuration the stream is not closing and not reaching EOF.
              request_header_mode: "SEND"
              response_header_mode: "SEND"
              request_body_mode: "BUFFERED"
              response_body_mode: "BUFFERED"
              request_trailer_mode: "SKIP"
              response_trailer_mode: "SKIP"

Once the response trailer mode is set to SEND the stream is closing properly. It should ideally work with SKIP mode also.

**Comment by alecholmez** [comment]
I think this is more of an Envoy issue. Can you open an issue here?
https://github.com/envoyproxy/envoy

**Comment by shibin-aot** [comment]
Sure, I will do that. Mistakenly raised the issue with control-plane
