### ISSUE TITLE
Relax consistency check for ADS

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/go-control-plane#63]
ADS mode requires a hold on the response until the entire set of snapshot names is requested (to simplify version tracking of partial name subsets). That means, `Snapshot` must be self-consistent when submitted to the cache; it should have as many cluster load assignments as there are clusters. However, the client of the library, may want to use one pool of cluster load assignments for all proxies and all snapshots. We should relax the consistency check to validate that the set of clusters is a _subset_ of cluster load assignments, not a precise match.

**Comment by sokac** [comment]
This strict check results in not being able to set zone aware routing with it. To enable zone aware routing, minimum configuration should be as follows:

`
cluster_manager:
  local_cluster_name: cluster_a
static_resources:
  clusters:
  - name: cluster_a
    type: EDS
    eds_cluster_config: ...
  - name: cluster_b
    type: EDS
    eds_cluster_config: ...
`
From: https://www.envoyproxy.io/docs/envoy/latest/faq/zone_aware_routing

In addition to this, our setup has ADS set in dynamic resources section.

What I observed is that envoy can't startup as the control plane is not responding (which is expected current behavior):

`
ADS mode: not responding to request: "cluster_c" not listed
`

However, if there's no connection to the control plane during startup phase and later is establish, Envoy picks it up and works as expected.

This is similar to following issue:
https://github.com/heptio/contour/pull/425

A patch to relax complexity could be following:

`
diff --git a/vendor/github.com/envoyproxy/go-control-plane/pkg/cache/simple.go b/vendor/github.com/envoyproxy/go-control-plane/pkg/cache/simple.go
index ed6e73d98..f03daab91 100644
--- a/vendor/github.com/envoyproxy/go-control-plane/pkg/cache/simple.go
+++ b/vendor/github.com/envoyproxy/go-control-plane/pkg/cache/simple.go
@@ -216,12 +216,13 @@ func (cache *snapshotCache) cancelWatch(nodeID string, watchID int64) func() {
 func (cache *snapshotCache) respond(request Request, value chan Response, resources map[string]Resource, version string) {
        // for ADS, the request names must match the snapshot names
        // if they do not, then the watch is never responded, and it is expected that envoy makes another request
+       resourcesFiltered := resources
        if len(request.ResourceNames) != 0 && cache.ads {
-               if err := superset(nameSet(request.ResourceNames), resources); err != nil {
-                       if cache.log != nil {
-                               cache.log.Infof("ADS mode: not responding to request: %v", err)
+               resourcesFiltered = make(map[string]Resource)
+               for name, _ := range nameSet(request.ResourceNames) {
+                       if res, ok := resources[name]; ok {
+                               resourcesFiltered[name] = res
                        }
-                       return
                }
        }
        if cache.log != nil {
@@ -229,7 +230,7 @@ func (cache *snapshotCache) respond(request Request, value chan Response, resour
                        request.TypeUrl, request.ResourceNames, request.VersionInfo, version)
        }
 
-       value <- createResponse(request, resources, version)
+       value <- createResponse(request, resourcesFiltered, version)
 }
 
 func createResponse(request Request, resources map[string]Resource, version string) Response {
`

Let me know if you think that's acceptable and I can go ahead and create a proper PR.

**Comment by kyessenov** [comment]
Hi,

I'm not very versed in zone aware routing with Envoy. I can explain why the restriction exists right now.
In ADS mode, the current implementation has minimal tracking of config pushes per node. To make this happen, the implementation holds a response until the full set of resources is requested. 

For example, if ADS server has {a,b,c}, and proxy requests {a,b}, the implementation does not return {a, b}. If it did, then it would have to generate a new resource version to replace {a, b} with {a, b, c}:

proxy: give me {a, b}
server: here {a, b} at snapshot version v0
proxy: give me {a, b, c} from v0
server: v0 is the latest, no need to push {c} (error!)

**Comment by sokac** [comment]
Thanks for the explanation. I guess the problem can be reproduced by having following config:

```
cluster_manager:
  local_cluster_name: cluster_a
dynamic_resources:
  ads_config:
    api_type: GRPC
    grpc_services:
      envoy_grpc:
        cluster_name: static_resources_cluster_ads
  cds_config:
    ads: {{}}
  lds_config:
    ads: {{}}
static_resources:
  clusters:
  - name: cluster_a
    type: EDS
    connect_timeout: 1s
    eds_cluster_config:
        eds_config:
          ads: {}
```

Let's assume there are N clusters defined for such node. Envoy gets stuck waiting for ADS response as ADS refuses to send response because only one cluster is requested and not N. The patch snippet solves this particular problem, but creates a different one - hence not acceptable.

Looking into code, looks like streaming/gRPC is not affected with the patch (since code is okay sending the same version over the wire), hence I didn't see any issues. HTTPGateway / Fetch method is affected, tho:
https://github.com/envoyproxy/go-control-plane/blob/master/pkg/server/server.go#L362
https://github.com/envoyproxy/go-control-plane/blob/master/pkg/cache/simple.go#L289

I'll check with Envoy maintainers does it make sense to have a timeout after which Envoy will resume starting up instead of waiting indefinitely. Otherwise, I'll try to come up with a generic solution for this project.

**Comment by kyessenov** [comment]
I think it might help to provide some a-priori knowledge to the management server about static resources (e.g. cluster_a in your example). The management server can act differently for a new node, by immediately responding to the full set of static resources with a special snapshot version, and then advancing to the complete snapshot only after LDS/CDS are processed.

For example, if envoy has cluster_a statically defined, and ADS pushes {cluster_b, cluster_c} at v1, then the following sequence seems appropriate:
1. EDS for cluster_a -> response with cluster_a at version v0.
2. EDS for cluster_a, cluster_b -> hold on cluster_b is dynamic and cluster_c not requested
3. EDS for cluster_a, cluster_b, cluster_c -> reply with version v1.
