### ISSUE TITLE
When discovery.DiscoveryRequest passes in the wrong type_ Url, raise panic！

### ISSUE THREAD

**Issue by zuige970126** [envoyproxy/go-control-plane#654]
![image](https://user-images.githubusercontent.com/65713439/223109307-b14fde8e-f4f0-426e-b01e-d6b36ff10b53.png)
/go-control-plane/pkg/server/sotw/v3/server.go:224
`			res, ok := value.Interface().(cache.Response)
			if !ok {
				return status.Errorf(codes.Unavailable, "value is nil, not cache.Response", index)
			}
`

**Comment by valerian-roche** [comment]
Can you provide a reproducer of the issue? 
This is currently not handled as this would show some corruption in the values return by the cache. Is it occurring when using a user-specific cache? 
Also feel free to raise a PR making this change and providing a test case to ensure this doesn't get rolled back later on
