### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by taion809** [envoyproxy/go-control-plane#68]
Hello,
I've been using the go-control-plane for a little bit now and in that time there have been several breaking changes to the API.  It's not a big deal but it's unexpected work.  My suggestion is to start tagging releases after a breaking change (`v0.8`, `v0.9`, `v0.10`, etc) so it's easier to pin specific versions in glide.

**Comment by kyessenov** [comment]
Hi, sorry about that! Yes, I'll start from the initial tag 0.1 in a moment.

**Comment by kyessenov** [comment]
Done. The upstream APIs are subject to strict compatibility requirements from now on. Hopefully, that should avoid all the churn we have caused.
