### ISSUE TITLE
Make `NodeHash` context aware

### ISSUE THREAD

**Issue by slonka** [envoyproxy/go-control-plane#680]
Hi go-control-plane community!

In [Kuma](https://github.com/kumahq/kuma) we'd need NodeHash https://github.com/envoyproxy/go-control-plane/blob/23109de99e424e970b35d6a1218c606dd2c9f241/pkg/cache/v3/status.go#L28 to receive a context. If there are no strong objections I'll happily create a PR.

Let me know what you think :)

**Comment by jpeach** [comment]
Can you describe the use case a bit more? Not everywhere that calls `(NodeHash).ID(node *core.Node)` has a context available. If you have a top-level context that you would pass in (e.g. a per-cache context), then you could attach that to your `NodeHash` implementation?

**Comment by slonka** [comment]
We are passing some metadata (tenant id - the control plane will be able to handle multiple tenants that do not share any data) in the stream context that we'd need for hashing so I think that wouldn't work.

The same way we pass the context in the callback (e.g. [here](https://github.com/envoyproxy/go-control-plane/blob/v0.11.0/pkg/server/delta/v3/server.go#L96)) I'd love to be able to pass it to a hasher from https://github.com/envoyproxy/go-control-plane/blob/v0.11.0/pkg/server/delta/v3/server.go#L231 to https://github.com/envoyproxy/go-control-plane/blob/v0.11.0/pkg/cache/v3/simple.go#L464.

If you checkout this commit - https://github.com/slonka/kuma/commit/e5851eaec82553ef5c22b5c6ca72efb669e9dc8f and run `Global Sync Delta KDS should add resource to global store after adding it to Zone` you'll see that the context in the hasher is not the same as the one in the reconciler.

**Comment by jpeach** [comment]
Sorry for the late reply. This sounds like it would require an API break, so that would need some careful thought and planning.

> you'll see that the context in the hasher is not the same as the one in the reconciler.

I didn't have the time to look at the code very thoroughly, but I think the hasher has to be deterministic for the lifetime of a cache. Can you explain the problem and how an extra context would help?

**Comment by slonka** [comment]
No problem :). We managed to do this using Node metadata. So I'm closing this for now.
