### ISSUE TITLE
New release to include recent RBAC proto changes

### ISSUE THREAD

**Issue by erm-g** [envoyproxy/go-control-plane#681]
Hello,

We [(gRPC team)](https://github.com/grpc) recently merged 2 PRs to Envoy introducing AuditLogger functionality for RBAC -

- [26453](https://github.com/envoyproxy/envoy/pull/26453)
- [26415](https://github.com/envoyproxy/envoy/pull/26415)

I see that related [directory](https://github.com/envoyproxy/go-control-plane/tree/main/envoy/config/rbac/v3) was refreshed 3 weeks ago - could you rerun the job?

gRPC Go depends on `github.com/envoyproxy/go-control-plane v0.11.0`, could you release the new version to include the latest RBAC changes?

**Comment by alecholmez** [comment]
Sure thing! We're trying to land one PR (sotw ordering) then I'd like to cut the release.

**Comment by alecholmez** [comment]
Released as v0.11.1!
