### ISSUE TITLE
Caching xDS responses

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/go-control-plane#7]
The management server has to maintain a cache of the desired configurations for all proxies in the mesh. Since there could be a lot more proxies that different configurations, it seems we want to be able to group proxy nodes into buckets.

Let's start with a generic bucketing function:
```go
function nodeGroup(proxy api.Node): string
```

For example, we can use the cluster field in the node to group API responses if the cluster corresponds to the service cluster. Alternatively, we can use the generic metadata field in the node message to assign configuration to proxies (e.g. in kubernetes, we may use pod labels to uniequely identify sidecars).

The cache is a map from the node group and response type to the desired response:
```go
var cache map[NodeGroup][ResponseType]proto.Message
```

**Comment by mattklein123** [comment]
For Lyft I think we basically need a bucket for a group, and then a bucket for canary also (which is a node concept). @junr03 can you work with @kyessenov to make sure we can accomplish this in the first version.
