### ISSUE TITLE
How to integrate envoy external authentication using the Kratos framework?

### ISSUE THREAD

**Issue by Mr-MaxWang** [envoyproxy/go-control-plane#708]
https://github.com/envoyproxy/go-control-plane/blob/d2149dcfa227e708617a7f752ac765e9df2d6dff/envoy/service/auth/v3/external_auth.pb.go#L682

Code generated by protoc-gen-go.
versions:
protoc-gen-go v1.28.1
protoc        v3.21.12
source: `envoy/service/auth/v3/external_auth.proto`

Parameter `s` is of type `*grpc.Server`, why not interface `grpc.ServerRegister`?

I wanted to integrate envoy external authentication using the Kratos framework, but couldn't register the Authorization service.

[Kratos example](https://github.com/go-kratos/examples/blob/c2d361cc712c8145b268b2bc5f2bdd884985510f/grpc-vite/server/internal/server/grpc.go#LL29C2-L29C2)

- `grpc-vite/server/internal/server/grpc.go`

```go
package server

import (
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/middleware/recovery"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	v1 "test/api/helloworld/v1"
	"test/internal/conf"
	"test/internal/service"
)

// NewGRPCServer new a gRPC server.
func NewGRPCServer(c *conf.Server, greeter *service.GreeterService, logger log.Logger) *grpc.Server {
	var opts = []grpc.ServerOption{
		grpc.Middleware(
			recovery.Recovery(),
		),
	}
	if c.Grpc.Network != "" {
		opts = append(opts, grpc.Network(c.Grpc.Network))
	}
	if c.Grpc.Addr != "" {
		opts = append(opts, grpc.Address(c.Grpc.Addr))
	}
	if c.Grpc.Timeout != nil {
		opts = append(opts, grpc.Timeout(c.Grpc.Timeout.AsDuration()))
	}
	srv := grpc.NewServer(opts...)
	v1.RegisterGreeterServer(srv, greeter)
	return srv
}
```

- `grpc-vite/server/api/helloworld/v1/greeter_grpc.pb.go`

```go
// ...
func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}
// ...
```

**Comment by jpeach** [comment]
In [external_auth.pb.go](https://github.com/envoyproxy/go-control-plane/blob/main/envoy/service/auth/v2/external_auth.pb.go), we have this generated registration code:
```Go
func RegisterAuthorizationServer(s *grpc.Server, srv AuthorizationServer) {
	s.RegisterService(&_Authorization_serviceDesc, srv)
}
```

The question is why isn't this getting generated with a `grpc.ServiceRegistrar` type as the first argument.

So, that grpc-go change was made in https://github.com/grpc/grpc-go/pull/3968, which implies that our protobuf code is generated with a proton toolchain prior to whatever version that change was released in. IIUC, the protobuf codeine is done by [io_bazel_rules_go](https://github.com/bazelbuild/rules_go) and envoy uses [v0.39.1](https://github.com/envoyproxy/envoy/blob/ba9a2a7b0ee700117a49f493ff72fe080c5c2b9e/bazel/repository_locations.bzl#L852-L869).

So maybe there's some knob in proton that we would tweak, or something in the envoy build system that we would need to update this. I don't really know what that would be though.

Probably blocked by (or should be implemented in conjunction with) #524.

**Comment by jpeach** [comment]
As for Kratos specifically, you'll need to find some way to get Kratos to give you the `*grpc.Server` for you to register the server interface with.

**Comment by noahziheng** [comment]
@Mr-MaxWang Actually you can use the original grpc.Server which combines within Kratos gRPC transport struct to register, like:

```golang
package server

import (
	"authserver/internal/conf"
	"authserver/internal/service"

	envoy_service_auth "github.com/envoyproxy/go-control-plane/envoy/service/auth/v3"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/middleware/logging"
	"github.com/go-kratos/kratos/v2/middleware/recovery"
	"github.com/go-kratos/kratos/v2/transport/grpc"
)

// NewGRPCServer new a gRPC server.
func NewGRPCServer(c *conf.Server, authSvc *service.AuthorizationService, logger log.Logger) *grpc.Server {
	var opts = []grpc.ServerOption{
		grpc.Middleware(
			logging.Server(logger),
			recovery.Recovery(),
		),
	}
	if c.Grpc.Network != "" {
		opts = append(opts, grpc.Network(c.Grpc.Network))
	}
	if c.Grpc.Addr != "" {
		opts = append(opts, grpc.Address(c.Grpc.Addr))
	}
	if c.Grpc.Timeout != nil {
		opts = append(opts, grpc.Timeout(c.Grpc.Timeout.AsDuration()))
	}
	srv := grpc.NewServer(opts...)
	envoy_service_auth.RegisterAuthorizationServer(srv.Server, authSvc)
	return srv
}
```
