### ISSUE TITLE
Requesting support for alt-port in healthcheck

### ISSUE THREAD

**Issue by pramodrj07** [envoyproxy/go-control-plane#764]
Is there a plan to enable an alt port for specifying health check in the proto and implementation?

https://github.com/envoyproxy/go-control-plane/blob/main/envoy/config/core/v3/health_check.pb.go#L186

we are looking to have this feature enabled. Also if there no bandwidth for the debs here, it would be great to have any pointers on how i can work towards enabling this?

**Comment by jpeach** [comment]
This would require making Envoy changes to implement the feature you want. It looks like you already filed an Envoy issue https://github.com/envoyproxy/envoy/issues/29033, to I think the best thing is to track the work there.
