### ISSUE TITLE
the resource order is not in line with the description in the xds doc

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/go-control-plane#800]
It looks like the current order is not in line with the description in the xds doc.

The order in the current implementation: Listener -> Route -> Cluster -> Endpoint
According to xds doc, the order should be like: Cluster -> Endpoint -> Listener -> Route 

References:

https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#eventual-consistency-considerations

```
In general, to avoid traffic drop, sequencing of updates should follow a make before break model, wherein:

CDS updates (if any) must always be pushed first.

EDS updates (if any) must arrive after CDS updates for the respective clusters.

LDS updates must arrive after corresponding CDS/EDS updates.

RDS updates related to the newly added listeners must arrive after CDS/EDS/LDS updates.

VHDS updates (if any) related to the newly added RouteConfigurations must arrive after RDS updates.

Stale CDS clusters and related EDS endpoints (ones no longer being referenced) can then be removed.
```

https://github.com/envoyproxy/go-control-plane/blob/52093cd01fd1a94d243081f6dec566db6987c145/pkg/cache/v3/order_test.go#L66-L71

**Comment by AmitKatyal-Sophos** [comment]
@zhaohuabing Thanks for creating the bug
