### ISSUE TITLE
Add MaxMind GeoIP Provider

### ISSUE THREAD

**Issue by zvlb** [envoyproxy/go-control-plane#808]
Hi all.
In new release envoy add [MaxMind GeoIP Provider in GeoIP HttpFilter](https://www.envoyproxy.io/docs/envoy/v1.28.0/api-v3/extensions/geoip_providers/maxmind/v3/maxmind.proto#envoy-v3-api-msg-extensions-geoip-providers-maxmind-v3-maxmindconfig).

But go-control-plane don't know about type_config `type.googleapis.com/envoy.extensions.geoip_providers.maxmind.v3.MaxMindConfig`

I have error, when I try unmarshal httpFilter with MaxMind GeoIP: 
```
 cannot unmarshal: proto: (line 1:202): unable to resolve "type.googleapis.com/envoy.extensions.geoip_providers.maxmind.v3.MaxMindConfig": "not found"
```

Can you add this Provider to go-control-plane protobuf?

**Comment by sunjayBhatia** [comment]
Looks like that has been mirrored here: https://github.com/envoyproxy/go-control-plane/blob/dc05a22efe95c6128f9ee9d206edc0c855a7961c/envoy/extensions/geoip_providers/maxmind/v3/maxmind.pb.go#L27

**Comment by zvlb** [comment]
Thank you. Is it possible to release a new version with this and the rest of the functionality that has been added since the last release in May?

**Comment by sunjayBhatia** [comment]
cc @alecholmez ^ or others that have release powers
