### ISSUE TITLE
inconsitent usage of context package

### ISSUE THREAD

**Issue by DennisRutjes** [envoyproxy/go-control-plane#81]
Generated API uses golang.org/x/net/context".Context should use context".Context

# github.com/envoyproxy/go-control-plane/pkg/server
../github.com/envoyproxy/go-control-plane/pkg/server/server.go:65:41: cannot use server literal (type *server) as type Server in return argument:
	*server does not implement Server (wrong type for FetchClusters method)
		have FetchClusters("context".Context, *"github.com/envoyproxy/go-control-plane/envoy/api/v2".DiscoveryRequest) (*"github.com/envoyproxy/go-control-plane/envoy/api/v2".DiscoveryResponse, error)
		want FetchClusters("golang.org/x/net/context".Context, *"github.com/envoyproxy/go-control-plane/envoy/api/v2".DiscoveryRequest) (*"github.com/envoyproxy/go-control-plane/envoy/api/v2".DiscoveryResponse, error)

Compilation finished with exit code 2

**Comment by kyessenov** [comment]
Can you please make sure you're using a recent version of Go? Type aliases were recently introduced to the language, and they get around this problem of legacy code using old struct names.

**Comment by DennisRutjes** [comment]
mm I am using 1.9.7?

**Comment by kyessenov** [comment]
Hmm, 1.9.7 should have type aliases. I saw this error before, but once I updated my dependencies it went away. I'll see if I can get rid of `x/net/context`. Some of it is coming from gRPC.

**Comment by DennisRutjes** [comment]
thanks in advance!

**Comment by DennisRutjes** [comment]
After I used go dep init for my project the issue was resolved!

so no urgency @kyessenov

**Comment by kyessenov** [comment]
Great. I'd prefer to keep using the old context package. There are some arguments here https://github.com/gogo/protobuf/issues/390.

**Comment by kyessenov** [comment]
Let's wait a few months before changing the package (so all the underlying gogo/go issues get ironed out).
