### ISSUE TITLE
Outlier detection event log

### ISSUE THREAD

**Issue by leandrocurioso** [envoyproxy/go-control-plane#827]
Hi I am using version 0.11.1 and I cannot set the event log path for outlier. How can this be done?

Another question is there a version that is compatible with envoy 0.28.0?

For instance there is a new attribute in envoy 0.28 for outlier config **successful_active_health_check_unject_host"* but I cannot set it in my go project because I cannot find this property.

**Comment by jpeach** [comment]
It's generally pretty safe to take a commit of go-control-plane that is later than the last release in order to pick up protobuf changes.
