### ISSUE TITLE
Release schedule for this project?

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/go-control-plane#832]
Is there any doc about when to kick off a release?
It seems that this project doesn't follow the same release schedule as Envoy. What if people want to use a new field added in the latest Envoy release, but this project hasn't provided a match release yet?

Thanks for your reply.

**Comment by craigjbass** [comment]
We've noticed a few outdated dependencies which could do with being updated in this project, and unsure what exactly the approach is to go control plane planning.

**Comment by michaelDovgal** [comment]
cc @alecholmez  ( I see that you are maintainer for the repo and made the latest releases)

**Comment by alecholmez** [comment]
We've been going back and forth on some release cycle stuff, once the multi-module release plan lands that will become a lot smoother. In the meantime I can cut another patch release that pulls in the latest envoy configurations.

**Comment by craigjbass** [comment]
Anything I can do to help?

**Comment by alecholmez** [comment]
Checking this out would help! https://github.com/envoyproxy/go-control-plane/pull/714

I've got some catching up to do on that but hopefully can get it in soon

**Comment by alecholmez** [comment]
I just pushed 0.12.0, but doesn't tackle the release schedule question yet.
