### ISSUE TITLE
Is there an equivalent to /v1/registration/service-name for EDS?

### ISSUE THREAD

**Issue by cdelguercio** [envoyproxy/go-control-plane#85]
I miss the status endpoint of the lyft/discovery reference SDS implementation. Is there a way to get the same information using the v2 messages?

**Comment by kyessenov** [comment]
You can use gRPC gateway that converts HTTP/1.1 requests into gRPC. See documentation: https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/lds.proto#L33, for example.

There is a sample gateway implementation here https://github.com/envoyproxy/go-control-plane/blob/master/pkg/server/gateway.go (or you can use gRPC generic one).
