### ISSUE TITLE
Deadlock in Delta XDS if number of resources is more than 10

### ISSUE THREAD

**Issue by lobkovilya** [envoyproxy/go-control-plane#875]
In [Kuma](https://github.com/kumahq/kuma) we're implementing the `ResourceSnapshot` interface and our snapshot has more than 20 distinct resource types. 

After upgrading to `v0.12.0` we see deadlocks on the server and it seems like it was caused by https://github.com/envoyproxy/go-control-plane/pull/752. AFAICT the potential deadlock was fixed by [increasing the channel capacity](https://github.com/envoyproxy/go-control-plane/pull/752/files#diff-2239e4e23a62885d2c0b6d6d6cc0b453adf1886d26f445d601b2f1dc57131360R26), but it's not fixed for us since our snapshot has more resource types.

I'm looking for help or advice on what'd be the best way to fix it? It doesn't seem right that `server` depends on the number of resource types in the snapshot to work properly.

**Comment by slonka** [comment]
There is a PR open so I wouldn't call it stale.

**Comment by lobkovilya** [comment]
Some additional context.

### Why the deadlock appeared after https://github.com/envoyproxy/go-control-plane/pull/752?

The PR replaces `a response channel per watch` model with `a response channel per all watches`. This was important to support ADS ordering, but at the same time, xDS was affected by the change.

### Why there is no deadlock in SotW?

SotW has 2 different implementations for [xds](https://github.com/envoyproxy/go-control-plane/blob/main/pkg/server/sotw/v3/xds.go) and [ads](https://github.com/envoyproxy/go-control-plane/blob/main/pkg/server/sotw/v3/ads.go). ADS has `a response channel per all watches` while xDS still has `a response channel per watch`.

### How the deadlock can be solved in Delta?

1. Introduce proper xDS implementation, so that the Delta server has both `xds.go` and `ads.go` similar to the SotW server.
2. Let the capacity of a response channel be configurable (see my PR https://github.com/envoyproxy/go-control-plane/pull/876)
3. Build some kind of an "unbounded channel" abstraction when the writer never blocks and the internal buffer is reallocated and shrunk dynamically (I know it's a tiny bit crazy idea 😅).

Probably there are some other options I haven't thought of. @valerian-roche @jpeach @alecholmez please take a look, I'd appreciate any input here, and I'd be happy to contribute the solution.

**Comment by valerian-roche** [comment]
Hey, sorry for the delay, I have not had much capacity to work on this recently. 
In my opinion the first proposal is not going in the correct direction. The sotw server implementation without ads ordering will also go away, as it is really inefficient on some aspects, and require additional maintenance effort. 
The second one as discussed would imo be pushing back dangerous complexity on the user. The risk of deadlock might be very hard to assess if an error is made by 1 for instance. 
My main proposal was to reimplement a part of the previous model, only for types not explicitly defined in the xds protocol as requiring ordering. This would allow the "unbounded behavior" of the previous implementation for users specifically using non-classic xds resources, while keeping ordering, and lower footprint of goroutines, for users only needing the basic types.

I plan on spending some time on the control-plane in Q2, though likely not in the coming weeks. If you want to take a stab at an implementation I can review it.

**Comment by lobkovilya** [comment]
Thanks for the reply @valerian-roche! 

> My main proposal was to reimplement a part of the previous model, only for types not explicitly defined in the xds protocol as requiring ordering. This would allow the "unbounded behavior" of the previous implementation for users specifically using non-classic xds resources, while keeping ordering, and lower footprint of goroutines, for users only needing the basic types.

Just checking my understanding, does it mean the `select` statement for Delta has to be re-implemented as `reflect.Select` in SotW?
https://github.com/envoyproxy/go-control-plane/blob/f2468473b7cde3c30a6824aacf350ff3c2a91c19/pkg/server/sotw/v3/xds.go#L53

So that each "not explicitly defined" type adds a `SelectCase` with its own `watch.response` channel?

**Comment by valerian-roche** [comment]
Hey, I'd like to not go in this direction. The old model of `sotw` is fundamentally different from the model of delta (even before the ads change), and aligning with it will require maintaining two entirely different loops. 
Prior to the ads change delta used to fork a [goroutine](https://github.com/envoyproxy/go-control-plane/pull/752/files#diff-5119f0079a6d464b74323939220b02d9a7aebcafd906e2e5be0161637afe5022L187) for each watch. I believe this can be reused if the resource of the watch is not a standard xds resource considered within the main channel buffering.
This would likely require having another muxed channel for those watches, as queuing in the other one could lead to deadlock, but adding an entry on the select should not create an issue

**Comment by lobkovilya** [comment]
If my understanding is correct, having another muxed channel for those watchers with the "default" capacity can still lead to deadlocks. Imagine two things happening simultaneously:
1. a goroutine on the server calls `SetSnapshot`
2. at the same time, the server receives a `DeltaDiscoveryRequest`


If the Snapshot contains more resource types than the "default" capacity, the `SetSnapshot` function might block when attempting to write to the new muxed channel, and during this block, [it holds the cache mutex](https://github.com/envoyproxy/go-control-plane/blob/f2468473b7cde3c30a6824aacf350ff3c2a91c19/pkg/cache/v3/simple.go#L225). At the same time, the server gets a `req` from `<-reqCh` in a select statement, it attempts to call either `watch.Cancel()` or `s.cache.CreateDeltaWatch(...)`. However, this action also gets blocked because the cache mutex is already held by the first goroutine. That's how we get a deadlock today.

That's why I brought up the `reflect.Select`. The ability to dynamically change select cases eliminates potential deadlocks. Regardless of the number of types in the `Snapshot`, the `SetSnapshot` never blocks with `reflect.Select`. So it's not really about aligning the code with SotW, I just don't see how else we can avoid the deadlock.

**Comment by lobkovilya** [comment]
@valerian-roche what do you think? Does it make sense to go with `reflect.Select` in Delta because of the reasons I mentioned above?

**Comment by lobkovilya** [comment]
Not stale, still the case

**Comment by lobkovilya** [comment]
Not stale, still the case
