### ISSUE TITLE
Is it possible to create a static layer?

### ISSUE THREAD

**Issue by leandrocurioso** [envoyproxy/go-control-plane#895]
I need to create a static layer like this.

https://www.envoyproxy.io/docs/envoy/v1.27.3/configuration/operations/runtime.html#layering

Is it possible with go control plane? If so can someone post a simple example please?

**Comment by valerian-roche** [comment]
Hey, the go-control-plane does not generate envoy configurations. It is only used as a core library to distribute the configurations provided to a fleet of xds clients.
Static layers are by definition not distributed by xDS (or more precisely rtDS), so this cannot be implemented through it. You can create an `rtds_layer` configured to connect to your control-plane and use the linear or snapshot cache in go-control-plane to populate the configuration to be served through it
