### ISSUE TITLE
How to avoid deprecated warning message for regex matcher?

### ISSUE THREAD

**Issue by leandrocurioso** [envoyproxy/go-control-plane#896]
Following this issue:

https://github.com/envoyproxy/envoy/issues/32685

How to do that in go control plane? Can someone post a simple example?

Thanks!

**Comment by valerian-roche** [comment]
Hey, the go-control-plane does not generate envoy configurations. It is only used as a core library to distribute the configurations provided to a fleet of xds clients.
To solve this issue you would need to contact the maintainers of the control-plane your clients are using to request them to remove this value. It might not be possible though, and there were discussions on the evolution of this deprecation in https://github.com/envoyproxy/envoy/issues/18633.
