### ISSUE TITLE
core.Healthcheck.{Timeout,Interval} use *types.Duration not *time.Duration

### ISSUE THREAD

**Issue by davecheney** [envoyproxy/go-control-plane#90]
The duration style fields in `core.Healthcheck` are defined using the gogo/types Duration struct
```
type HealthCheck struct {
	// The time to wait for a health check response. If the timeout is reached the
	// health check attempt will be considered a failure.
	Timeout *google_protobuf3.Duration `protobuf:"bytes,1,opt,name=timeout" json:"timeout,omitempty"`
	// The interval between health checks.
	Interval *google_protobuf3.Duration `protobuf:"bytes,2,opt,name=interval" json:"interval,omitempty"`
```
Elsewhere in the core package the more convenient time Duration type is used
```
type ApiConfigSource struct {
        // ...
	RefreshDelay *time.Duration `protobuf:"bytes,3,opt,name=refresh_delay,json=refreshDelay,stdduration" json:"refresh_delay,omitempty"`
}
```
Why are there differences in the two definitions? Is it possible to change Healthcheck to use *time.Duration?

**Comment by kyessenov** [comment]
The difference is because of gogoproto annotation. I assume health check proto is new, so it was not annotated manually. I will take a look at the new changes in envoy protos, and update the annotations.

**Comment by davecheney** [comment]
Thank you. If you could update those with the correct annotations that
would be wonderful!

Is that something you'd also like to see contributions for? Or should I
stick to raising issues?

**Comment by kyessenov** [comment]
You are welcome to send patches to envoy protos for things like this. It's not changing bits on the wire, but improves developer experience when dealing with these protos. I'll do it this time, since it's an easy fix, and cc you.

**Comment by davecheney** [comment]
Thanks, that'll give me a pattern to follow.

**Comment by kyessenov** [comment]
This is amazing. Someone beat me to it and updated those protos already: https://github.com/envoyproxy/data-plane-api/commit/1834c1b9471e36a016215b931b5bf095fb7db0c9

Sent a PR here to pick it up.
