### ISSUE TITLE
Snapshot with empty version

### ISSUE THREAD

**Issue by pravinpushkar** [envoyproxy/go-control-plane#915]
I have a query below.

I pass a valid resource and a version (lets say 1) to below method - 

```go
snapshot, err = cachev3.NewSnapshot(version, resources)
```
In the next update, I am expecting to pass nil/empty resource and version 2 to above call. 
I was hoping that it would generate a snapshot with updated version and empty resources, but I get something like this - 

```
&{[{ map[]} { map[]}} 

# instead of 
&{[{ version: 2 map[]} { version:2 map[]}}
```

Because of version not present in new snapshot the `RespondDelta` gives empty version like this and my envoy config does not get updated in time.
```
open delta watch ID:2 for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret Resources:map[] from nodeID: "XXX",  version ""
```

Is there way to handle this situation or is this behaviour expected because of any reason  ?

**Comment by valerian-roche** [comment]
Hey,
From the current implementation at https://github.com/envoyproxy/go-control-plane/blob/main/pkg/cache/v3/snapshot.go#L51, you need to provide the types you are explicitly setting to "empty". The current snapshot cache code work with a logic per type (even if the current snapshot API "constructors" don't let you set distinct versions). This could be used for instance to avoid sending updates for unchanged types in sotw version if nothing has changed for a given type
