### ISSUE TITLE
Support ext_authz: Added support for populating the tls_session for extensions.filters.network.ext_authz.v3.ExtAuthz

### ISSUE THREAD

**Issue by marc-barry** [envoyproxy/go-control-plane#936]
In https://www.envoyproxy.io/docs/envoy/v1.30.0/version_history/v1.30/v1.30.0 and via https://github.com/envoyproxy/envoy/pull/33105 there was support added for the following:

> ext_authz: Added support for populating the [tls_session](https://www.envoyproxy.io/docs/envoy/v1.30.0/api-v3/service/auth/v3/attribute_context.proto#envoy-v3-api-field-service-auth-v3-attributecontext-tls-session) check request attribute for network ext_authz by setting [include_tls_session](https://www.envoyproxy.io/docs/envoy/v1.30.0/configuration/listeners/network_filters/ext_authz_filter#config-network-filters-ext-authz) to true.

Is there a way I can work around the Go side not supporting that new functionality? It is documented under https://www.envoyproxy.io/docs/envoy/v1.30.0/api-v3/extensions/filters/network/ext_authz/v3/ext_authz.proto#envoy-v3-api-msg-extensions-filters-network-ext-authz-v3-extauthz. I'm trying to find out how I can effectively hack this in while we wait for the `go-control-plane` to catch up to the latest features of Envoy.

**Comment by sunjayBhatia** [comment]
Envoy repo APIs are automatically mirrored into this repo, see: https://github.com/envoyproxy/go-control-plane/blob/bc7bb4ca8b9d537c4bdda0076e807c0354df579a/envoy/extensions/filters/network/ext_authz/v3/ext_authz.pb.go#L66

**Comment by marc-barry** [comment]
> Envoy repo APIs are automatically mirrored into this repo, see:

@sunjayBhatia OK. I uses releases under https://github.com/envoyproxy/go-control-plane/releases/tag/v0.12.0 and so I guess I need to bypass that and pull in the latest `main` branch changes. Is this typically safe to do instead of waiting until a new release is made? At what cadence is a new release created?

**Comment by valerian-roche** [comment]
We do not create releases regularly recently. There is ongoing work to split the API module to allow independent versioning in #714

**Comment by marc-barry** [comment]
> We do not create releases regularly recently. There is ongoing work to split the API module to allow independent versioning in #714

Thanks for the reference. I'll close this off as I have the information I need and I'll follow #714 for the topic of releases.
