### ISSUE TITLE
When is the next planned release?

### ISSUE THREAD

**Issue by easwars** [envoyproxy/go-control-plane#961]
The [latest release](https://github.com/envoyproxy/go-control-plane/releases/tag/v0.12.0) is close to 6 months old.

gRPC-Go has a dependency on the generated protos here, and we would like to pin our dependency to a release version instead of a commit hash, and therefore would really appreciate if a new release is cut.

There is already an open issue for 1.x here: https://github.com/envoyproxy/go-control-plane/issues/391, but I would at least like to see a v0.13.0 in the near future.

Thanks.

**Comment by easwars** [comment]
Is there any update on this? Thanks

**Comment by jh125486** [comment]
Envoy v1.31.0 has been released for two weeks... can we get a new tagged release for the control plane?

**Comment by valerian-roche** [comment]
We usually do not create releases of the control-plane tracking envoy versions. There is ongoing work to split the generated api as a sub-module that could track envoy releases (as well as remove the need to source the entire repository to just source the api part)

**Comment by jh125486** [comment]
> We usually do not create releases of the control-plane tracking envoy versions. There is ongoing work to split the generated api as a sub-module that could track envoy releases (as well as remove the need to source the entire repository to just source the api part)

Let me know if you need any help... we use the protobuf-generated Go files in `go-control-plane` instead of submoduling Envoy and generating them ourselves. (Mostly because submodules don't have great devx and cause havoc in our CI/CD sometimes.)
